-- GENERATED by python/design_decimator.py -- DO NOT EDIT BY HAND.
-- Regenerate with:  python python/design_decimator.py
--
-- 96 kHz -> 24 kHz decimation, two cascaded halfband FIR stages.
-- Passband 0-11000 Hz, stopband from 13000 Hz.
-- Only NON-ZERO taps are listed; a halfband's even taps are exactly
-- zero and the datapath skips them. IDX is the tap position in the
-- full-length filter, which is what the delay-line address must use.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package decim_coef_pkg is

    constant C_COEF_BITS : integer := 20;
    constant C_DATA_BITS : integer := 24;
    -- Worst case sum(|coef|) x max|data|, not a tap-count estimate.
    constant C_ACC_BITS  : integer := 45;

    constant C_N1 : integer := 27;   -- stage 1 length, 96k -> 48k
    constant C_N2 : integer := 171;  -- stage 2 length, 48k -> 24k
    constant C_NZ1 : integer := 15;  -- non-zero taps, stage 1
    constant C_NZ2 : integer := 87;  -- non-zero taps, stage 2

    type coef_array is array (natural range <>) of signed(C_COEF_BITS-1 downto 0);
    type idx_array  is array (natural range <>) of integer;

    -- stage 1: 15 non-zero of 27 taps
    constant C_COEF1 : coef_array(0 to 14) := (
        to_signed(4, C_COEF_BITS), to_signed(-247, C_COEF_BITS), to_signed(2052, C_COEF_BITS), to_signed(-9223, C_COEF_BITS),
        to_signed(29843, C_COEF_BITS), to_signed(-83845, C_COEF_BITS), to_signed(323560, C_COEF_BITS), to_signed(524287, C_COEF_BITS),
        to_signed(323560, C_COEF_BITS), to_signed(-83845, C_COEF_BITS), to_signed(29843, C_COEF_BITS), to_signed(-9223, C_COEF_BITS),
        to_signed(2052, C_COEF_BITS), to_signed(-247, C_COEF_BITS), to_signed(4, C_COEF_BITS)
    );
    constant C_IDX1 : idx_array(0 to 14) := (
        0, 2, 4, 6, 8, 10, 12, 13, 14, 16, 18, 20,
        22, 24, 26
    );

    -- stage 2: 87 non-zero of 171 taps
    constant C_COEF2 : coef_array(0 to 86) := (
        to_signed(1, C_COEF_BITS), to_signed(-2, C_COEF_BITS), to_signed(4, C_COEF_BITS), to_signed(-7, C_COEF_BITS),
        to_signed(12, C_COEF_BITS), to_signed(-19, C_COEF_BITS), to_signed(30, C_COEF_BITS), to_signed(-45, C_COEF_BITS),
        to_signed(66, C_COEF_BITS), to_signed(-93, C_COEF_BITS), to_signed(129, C_COEF_BITS), to_signed(-175, C_COEF_BITS),
        to_signed(234, C_COEF_BITS), to_signed(-308, C_COEF_BITS), to_signed(399, C_COEF_BITS), to_signed(-511, C_COEF_BITS),
        to_signed(648, C_COEF_BITS), to_signed(-813, C_COEF_BITS), to_signed(1011, C_COEF_BITS), to_signed(-1245, C_COEF_BITS),
        to_signed(1522, C_COEF_BITS), to_signed(-1847, C_COEF_BITS), to_signed(2227, C_COEF_BITS), to_signed(-2668, C_COEF_BITS),
        to_signed(3179, C_COEF_BITS), to_signed(-3770, C_COEF_BITS), to_signed(4451, C_COEF_BITS), to_signed(-5235, C_COEF_BITS),
        to_signed(6140, C_COEF_BITS), to_signed(-7186, C_COEF_BITS), to_signed(8400, C_COEF_BITS), to_signed(-9817, C_COEF_BITS),
        to_signed(11486, C_COEF_BITS), to_signed(-13475, C_COEF_BITS), to_signed(15886, C_COEF_BITS), to_signed(-18876, C_COEF_BITS),
        to_signed(22695, C_COEF_BITS), to_signed(-27782, C_COEF_BITS), to_signed(34963, C_COEF_BITS), to_signed(-46013, C_COEF_BITS),
        to_signed(65553, C_COEF_BITS), to_signed(-110533, C_COEF_BITS), to_signed(333529, C_COEF_BITS), to_signed(524287, C_COEF_BITS),
        to_signed(333529, C_COEF_BITS), to_signed(-110533, C_COEF_BITS), to_signed(65553, C_COEF_BITS), to_signed(-46013, C_COEF_BITS),
        to_signed(34963, C_COEF_BITS), to_signed(-27782, C_COEF_BITS), to_signed(22695, C_COEF_BITS), to_signed(-18876, C_COEF_BITS),
        to_signed(15886, C_COEF_BITS), to_signed(-13475, C_COEF_BITS), to_signed(11486, C_COEF_BITS), to_signed(-9817, C_COEF_BITS),
        to_signed(8400, C_COEF_BITS), to_signed(-7186, C_COEF_BITS), to_signed(6140, C_COEF_BITS), to_signed(-5235, C_COEF_BITS),
        to_signed(4451, C_COEF_BITS), to_signed(-3770, C_COEF_BITS), to_signed(3179, C_COEF_BITS), to_signed(-2668, C_COEF_BITS),
        to_signed(2227, C_COEF_BITS), to_signed(-1847, C_COEF_BITS), to_signed(1522, C_COEF_BITS), to_signed(-1245, C_COEF_BITS),
        to_signed(1011, C_COEF_BITS), to_signed(-813, C_COEF_BITS), to_signed(648, C_COEF_BITS), to_signed(-511, C_COEF_BITS),
        to_signed(399, C_COEF_BITS), to_signed(-308, C_COEF_BITS), to_signed(234, C_COEF_BITS), to_signed(-175, C_COEF_BITS),
        to_signed(129, C_COEF_BITS), to_signed(-93, C_COEF_BITS), to_signed(66, C_COEF_BITS), to_signed(-45, C_COEF_BITS),
        to_signed(30, C_COEF_BITS), to_signed(-19, C_COEF_BITS), to_signed(12, C_COEF_BITS), to_signed(-7, C_COEF_BITS),
        to_signed(4, C_COEF_BITS), to_signed(-2, C_COEF_BITS), to_signed(1, C_COEF_BITS)
    );
    constant C_IDX2 : idx_array(0 to 86) := (
        0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22,
        24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46,
        48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 85, 86, 88, 90, 92,
        94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116,
        118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140,
        142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164,
        166, 168, 170
    );

end package decim_coef_pkg;
