library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.decim_coef_pkg.all;

-- ---------------------------------------------------------------------------
-- 96 kHz -> 24 kHz decimation for all 16 channels.
--
-- Two cascaded halfband FIR stages: 96k -> 48k -> 24k. Coefficients come from
-- decim_coef_pkg, generated by python/design_decimator.py. Measured on the
-- quantised cascade: 0.00015 dB passband ripple to 11 kHz, -102.5 dB worst
-- alias band, 1.91 ms group delay. See docs/DECIMATION.md for why halfband FIR
-- and not CIC - a CIC droops 9.2 dB at 11 kHz and gives only 4.1 dB of alias
-- rejection at 13 kHz, which is useless for a band reaching 92% of Nyquist.
--
-- ------------------------------- STRUCTURE -------------------------------
-- TWO INDEPENDENT FREE-RUNNING ENGINES, one per stage, each with its own
-- multiplier and its own delay RAM. They never contend for anything.
--
-- This is NOT the obvious "do all the work when a sample arrives" burst
-- schedule. That does not fit: a frame needing both stages is 16 x (8 + 44) =
-- 832 multiplies against the 256 clk cycles between 96 kHz samples. Spreading
-- both stages across one shared multiplier is 112% of the cycle budget - still
-- over. Two multipliers, each free-running against its own deadline, is what
-- fits, and it fits with room:
--
--     engine 1   fires every 2 frames ( 512 cyc)  uses 192  ->  38%
--     engine 2   fires every 4 frames (1024 cyc)  uses 768  ->  75%
--
-- Cyclone IV EP4CE6 has 30 multipliers and the shipping build uses ZERO, while
-- LEs are at 64% (4,025 of 6,272) and registers at 3,047. Sixteen parallel FIR
-- instances would need thousands more registers than exist - Cyclone IV E has
-- one flip-flop per LE and no LUT-based distributed RAM. So this design spends
-- the multipliers and M9K that are idle rather than the LEs that are nearly
-- gone.
--
-- Symmetry folding: linear phase means coefficient k equals coefficient
-- (N-1-k), so the two taps are pre-added and multiplied once. The delay RAM is
-- true dual-port to fetch both in one cycle. That halves the multiply count and
-- is what brings engine 2 under its deadline.
--
-- --------------------------- INTERFACE CONTRACT ---------------------------
-- data_in/valid_in match tdm16_merge's output exactly; data_out/valid_out match
-- what packet_formatter expects. Drop-in between them, no slot decoder or
-- encoder needed - the merged bus is already a parallel snapshot of all 16
-- channels, not a serial stream.
--
-- valid_out PULSES AT 24 kHz, NOT 96 kHz. Downstream must wait for the strobe
-- rather than assume a sample every frame. This is the classic decimator
-- integration bug, and here it would present as a 4x packet rate with repeated
-- samples - the same signature as the tdm16_merge level-vs-edge bug fixed in
-- 927aac7.
--
-- Channel order is preserved exactly: data_in(383 downto 192) is ch 1-8 and
-- (191 downto 0) is ch 9-16, per tdm16_merge. data_out uses the same layout, so
-- the UDP payload, every host script, and the byte-60 phantom readback are all
-- untouched.
--
-- All 16 channels are written to the delay lines on the SAME strobe and read by
-- the SAME schedule, so they stay mutually sample-aligned by construction.
-- That is what GCC-PHAT cross-correlation needs, and it is a structural
-- property here rather than something to verify per channel.
-- ---------------------------------------------------------------------------

entity decimator is
    port (
        clk       : in  std_logic;                       -- clk_18m, 24.576 MHz
        rst       : in  std_logic;
        data_in   : in  std_logic_vector(383 downto 0);  -- 16 ch x 24 bit, 96 kHz
        valid_in  : in  std_logic;                       -- 1 clk pulse per frame
        data_out  : out std_logic_vector(383 downto 0);  -- 16 ch x 24 bit, 24 kHz
        valid_out : out std_logic;                       -- 1 clk pulse, 24 kHz
        saturated : out std_logic                        -- sticky, see round_sat
    );
end entity decimator;

architecture rtl of decimator is

    constant CH : integer := 16;
    constant DW : integer := C_DATA_BITS;      -- 24

    -- Delay-line depth per channel, rounded up to a power of two so the address
    -- is {channel, tap} concatenation instead of a multiply. A multiplier spent
    -- on address arithmetic would be absurd when the whole design exists to
    -- spend as few as possible.
    constant D1 : integer := 32;               -- >= C_N1  (27)
    constant D2 : integer := C_N2;             -- exactly 171, see below
    constant AW1 : integer := 5;               -- log2(D1)
    constant AW2 : integer := 8;               -- covers D2 = 171
    --
    -- NEVER WRITE "mod D2" HERE. D2 was briefly 192, and the mod operator
    -- synthesised into two lpm_divide instances - 282 LEs of real hardware
    -- divider on a device with none to spare. The wrap is done by conditional
    -- subtract below instead, which is one comparator.
    --
    -- D1 is a power of two so its pointer wraps for free. D2 is NOT padded to
    -- 256: at 24 bits deep x 16 channels that would be 4096 words = 16 M9K per
    -- copy and 32 for the pair, over the device's 30. Exact depth is 11 per
    -- copy, 22 for the pair. The padding that costs nothing in LEs costs the
    -- whole fit in memory blocks.

    type ram1_t is array (0 to CH*D1-1) of std_logic_vector(DW-1 downto 0);
    type ram2_t is array (0 to CH*D2-1) of std_logic_vector(DW-1 downto 0);

    -- TWO COPIES OF EACH DELAY LINE, HELD IDENTICAL.
    --
    -- Symmetry folding needs two samples per cycle, and a write port as well.
    -- An M9K has exactly two ports, so 2R+1W does not fit in one block. Each
    -- copy therefore carries 1 write + 1 read, which is the simple dual-port
    -- form Quartus infers directly. The duplication costs memory bits, which
    -- is the resource in surplus here (19.6 of 30 M9K used), and buys back the
    -- cycle budget, which is not.
    --
    -- The two copies are written from the same statement with the same data on
    -- the same cycle, so they cannot diverge.
    signal ram1_a, ram1_b : ram1_t := (others => (others => '0'));

    -- Stage 2 is a SINGLE true-dual-port RAM, not a duplicated pair.
    --
    -- ram2 is by far the largest array (16 ch x 171 taps x 24 bit = 2736 words
    -- = 11 M9K). Duplicating it costs 22 of the device's 30 blocks and the fit
    -- fails - memory BLOCKS, not memory bits, are the binding resource here:
    -- at 24-bit width an M9K holds only 256 words, so 60% bit utilisation can
    -- still exhaust the block count.
    --
    -- Instead both symmetric taps are read from one true-dual-port RAM using
    -- its two independent read addresses, and the occasional write from
    -- engine 1 steals a cycle. That is 16 stalls per 4 frames against 1024
    -- cycles - engine 2 goes from 75% to 77% utilised, and the pair of arrays
    -- becomes 11 blocks instead of 22.
    signal ram2 : ram2_t := (others => (others => '0'));

    -- ramstyle is a hint; inference depends on the access pattern being a
    -- single synchronous read and a single synchronous write. If Quartus ever
    -- infers registers instead, the fit fails loudly on LE count rather than
    -- silently degrading.
    attribute ramstyle : string;
    attribute ramstyle of ram1_a : signal is "M9K";
    attribute ramstyle of ram1_b : signal is "M9K";
    attribute ramstyle of ram2 : signal is "M9K";

    -- Write pointers. Shared across channels: every channel is written on the
    -- same strobe, so one pointer keeps all 16 in lockstep.
    signal wp1 : unsigned(AW1-1 downto 0) := (others => '0');
    signal wp2 : unsigned(AW2-1 downto 0) := (others => '0');

    -- Read bases: the newest written slot. Latched when an engine starts so the
    -- pointer cannot move underneath a burst in progress.
    signal rp1 : unsigned(AW1-1 downto 0) := (others => '0');
    signal rp2 : unsigned(AW2-1 downto 0) := (others => '0');

    -- Phase counters. Stage 1 outputs every 2nd input frame, stage 2 every 2nd
    -- stage-1 output - decimate by 2 twice, giving 4 overall.
    signal ph1 : std_logic := '0';
    signal ph2 : std_logic := '0';   -- stage-2 half-rate phase

    -- Sequential input-write path (see the process comment below).
    signal in_reg   : std_logic_vector(383 downto 0) := (others => '0');
    signal wr_busy  : std_logic := '0';
    signal wr_ch    : integer range 0 to CH-1 := 0;
    signal wr1_en   : std_logic := '0';
    signal wr1_addr : integer range 0 to CH*D1-1 := 0;
    signal wr1_data : std_logic_vector(DW-1 downto 0) := (others => '0');
    signal wr2_en   : std_logic := '0';
    signal wr2_addr : integer range 0 to CH*D2-1 := 0;
    signal wr2_data : std_logic_vector(DW-1 downto 0) := (others => '0');

    -- Engine 1: 96k -> 48k
    type st1_t is (E1_IDLE, E1_ADDR, E1_MAC, E1_DONE);
    signal st1   : st1_t := E1_IDLE;
    signal ch1   : integer range 0 to CH-1 := 0;
    signal tap1  : integer range 0 to 15 := 0;
    signal acc1  : signed(C_ACC_BITS-1 downto 0) := (others => '0');
    signal a1_a, a1_b : signed(DW-1 downto 0) := (others => '0');
    signal cf1   : signed(C_COEF_BITS-1 downto 0) := (others => '0');
    signal mid1  : std_logic := '0';
    signal vld1  : std_logic := '0';
    signal e1_go : std_logic := '0';

    -- Engine 2: 48k -> 24k
    type st2_t is (E2_IDLE, E2_ADDR, E2_MAC, E2_DONE);
    signal st2   : st2_t := E2_IDLE;
    signal ch2   : integer range 0 to CH-1 := 0;
    signal tap2  : integer range 0 to 63 := 0;
    signal acc2  : signed(C_ACC_BITS-1 downto 0) := (others => '0');
    signal a2_a, a2_b : signed(DW-1 downto 0) := (others => '0');
    signal cf2   : signed(C_COEF_BITS-1 downto 0) := (others => '0');
    signal mid2  : std_logic := '0';
    signal e2_go : std_logic := '0';

    signal out_reg : std_logic_vector(383 downto 0) := (others => '0');
    signal vout_r  : std_logic := '0';

    -- Saturation is detected in both engines, so each latches its own flag and
    -- the two are OR-ed combinationally. One signal written by two processes is
    -- multiple constant drivers - Quartus rejects it outright (Error 10028),
    -- which is the correct behaviour and how this was caught.
    signal sat1_r  : std_logic := '0';
    signal sat2_r  : std_logic := '0';

    -- Folded tap counts: only the first half of the symmetric response is
    -- walked, the mirror being folded in by the pre-add.
    constant F1 : integer := (C_NZ1 + 1) / 2;   -- 8
    constant F2 : integer := (C_NZ2 + 1) / 2;   -- 44

    -- Rounding back to 24 bits.
    --
    -- Coefficients are scaled to 2^(C_COEF_BITS-1)-1 at unity DC gain, so the
    -- accumulator is shifted right by (C_COEF_BITS-1) to return to input scale.
    -- Round-to-nearest, which MUST match the Python reference model - the
    -- vectors in sim/decim_ref_vectors.txt will not match a truncating
    -- implementation, and truncation would also put a -0.5 LSB DC offset on
    -- every channel.
    --
    -- Saturation cannot trigger for unity DC gain and bounded input, but on
    -- overflow the alternative is wraparound, which turns a small numerical
    -- error into a full-scale impulse - a broadband click that would wreck a
    -- correlation. `saturated` publishes it so the condition is observable
    -- instead of silent.
    constant SH : integer := C_COEF_BITS - 1;

    function round_sat(a : signed) return signed is
        variable r   : signed(a'length-1 downto 0);
        variable lim : signed(a'length-1 downto 0);
    begin
        r := shift_right(a + to_signed(2**(SH-1), a'length), SH);
        lim := to_signed(2**(DW-1) - 1, a'length);
        if r > lim then
            return lim(DW-1 downto 0);
        elsif r < -lim then
            return resize(-lim(DW-1 downto 0), DW);
        else
            return r(DW-1 downto 0);
        end if;
    end function;

    function is_sat(a : signed) return boolean is
        variable r   : signed(a'length-1 downto 0);
        variable lim : signed(a'length-1 downto 0);
    begin
        r := shift_right(a + to_signed(2**(SH-1), a'length), SH);
        lim := to_signed(2**(DW-1) - 1, a'length);
        return (r > lim) or (r < -lim);
    end function;

begin

    data_out  <= out_reg;
    valid_out <= vout_r;
    saturated <= sat1_r or sat2_r;

    -- =====================================================================
    -- Input capture and stage-1 delay-line write.
    -- All 16 channels land on one strobe, which is what keeps them aligned.
    -- =====================================================================
    -- The frame is latched, then written one channel per cycle. A 16-wide
    -- parallel write would need 16 write ports and blocks RAM inference
    -- entirely; sequential costs 16 of the 256 cycles per frame (6%) and
    -- infers cleanly. All 16 still land before any engine reads them, so they
    -- remain a single coherent frame.
    process(clk, rst)
    begin
        if rst = '1' then
            wp1     <= (others => '0');
            ph1     <= '0';
            e1_go   <= '0';
            wr_busy <= '0';
            wr_ch   <= 0;
        elsif rising_edge(clk) then
            e1_go   <= '0';
            wr1_en  <= '0';

            if valid_in = '1' then
                in_reg  <= data_in;
                wr_ch   <= 0;
                wr_busy <= '1';
            elsif wr_busy = '1' then
                wr1_en   <= '1';
                wr1_addr <= wr_ch*D1 + to_integer(wp1);
                wr1_data <= in_reg(383 - wr_ch*DW downto 384 - (wr_ch+1)*DW);

                if wr_ch = CH-1 then
                    wr_busy <= '0';
                    -- Stage 1 produces an output every second input frame.
                    if ph1 = '1' then
                        e1_go <= '1';
                    end if;
                    ph1 <= not ph1;
                    wp1 <= wp1 + 1;
                else
                    wr_ch <= wr_ch + 1;
                end if;
            end if;
        end if;
    end process;

    -- Single write port, both copies, same cycle.
    process(clk)
    begin
        if rising_edge(clk) then
            if wr1_en = '1' then
                ram1_a(wr1_addr) <= wr1_data;
                ram1_b(wr1_addr) <= wr1_data;
            end if;
        end if;
    end process;

    -- =====================================================================
    -- Engine 1: 96 kHz -> 48 kHz.  16 channels x 8 folded taps = 192 cycles,
    -- against 512 available. 38% utilised.
    -- =====================================================================
    process(clk, rst)
        variable pre  : signed(DW downto 0);
        variable prod : signed(DW + C_COEF_BITS downto 0);
        variable ia, ib : integer;
    begin
        if rst = '1' then
            st1  <= E1_IDLE;
            ch1  <= 0;
            tap1 <= 0;
            acc1  <= (others => '0');
            vld1   <= '0';
            wp2    <= (others => '0');
            sat1_r <= '0';
            wr2_en <= '0';
        elsif rising_edge(clk) then
            vld1   <= '0';
            wr2_en <= '0';

            case st1 is
                when E1_IDLE =>
                    if e1_go = '1' then
                        ch1  <= 0;
                        tap1 <= 0;
                        acc1 <= (others => '0');
                        rp1  <= wp1 - 1;      -- newest sample written
                        st1  <= E1_ADDR;
                    end if;

                -- Present both symmetric tap addresses. M9K is synchronous, so
                -- the data is available in the next state.
                when E1_ADDR =>
                    -- Unsigned pointer arithmetic wraps naturally at the RAM
                    -- depth, so no mod operator and no divider is inferred.
                    ia := ch1*D1 + to_integer(rp1 - to_unsigned(C_IDX1(tap1), AW1));
                    ib := ch1*D1 + to_integer(rp1 - to_unsigned(C_N1-1 - C_IDX1(tap1), AW1));
                    a1_a <= signed(ram1_a(ia));
                    a1_b <= signed(ram1_b(ib));
                    cf1  <= C_COEF1(tap1);
                    if C_IDX1(tap1) = (C_N1-1)/2 then
                        mid1 <= '1';       -- centre tap is its own mirror
                    else
                        mid1 <= '0';
                    end if;
                    st1 <= E1_MAC;

                when E1_MAC =>
                    if mid1 = '1' then
                        pre := resize(a1_a, DW+1);
                    else
                        pre := resize(a1_a, DW+1) + resize(a1_b, DW+1);
                    end if;
                    prod := pre * cf1;
                    acc1 <= acc1 + resize(prod, C_ACC_BITS);

                    if tap1 = F1-1 then
                        st1 <= E1_DONE;
                    else
                        tap1 <= tap1 + 1;
                        st1  <= E1_ADDR;
                    end if;

                when E1_DONE =>
                    if is_sat(acc1) then
                        sat1_r <= '1';
                    end if;
                    wr2_en   <= '1';
                    wr2_addr <= ch1*D2 + to_integer(wp2);
                    wr2_data <= std_logic_vector(round_sat(acc1));
                    acc1 <= (others => '0');
                    tap1 <= 0;

                    if ch1 = CH-1 then
                        vld1 <= '1';          -- whole frame written
                        -- D2 is not a power of two, so wrap explicitly.
                        if wp2 = D2-1 then
                            wp2 <= (others => '0');
                        else
                            wp2 <= wp2 + 1;
                        end if;
                        st1  <= E1_IDLE;
                    else
                        ch1 <= ch1 + 1;
                        st1 <= E1_ADDR;
                    end if;
            end case;
        end if;
    end process;

    -- Stage 2 fires on every second stage-1 output.
    process(clk, rst)
    begin
        if rst = '1' then
            e2_go <= '0';
            ph2   <= '0';
        elsif rising_edge(clk) then
            e2_go <= '0';
            if vld1 = '1' then
                if ph2 = '1' then
                    e2_go <= '1';
                end if;
                ph2 <= not ph2;
            end if;
        end if;
    end process;

    -- =====================================================================
    -- Engine 2: 48 kHz -> 24 kHz.  16 channels x 44 folded taps = 768 cycles,
    -- against 1024 available. 75% utilised - the tightest path in the design,
    -- and the reason stage 2's length is not tuned by hand.
    -- =====================================================================
    process(clk, rst)
        variable pre  : signed(DW downto 0);
        variable prod : signed(DW + C_COEF_BITS downto 0);
        variable ia, ib : integer;
        variable oa, ob : integer;
    begin
        if rst = '1' then
            st2   <= E2_IDLE;
            ch2   <= 0;
            tap2  <= 0;
            acc2   <= (others => '0');
            rp2    <= (others => '0');
            vout_r <= '0';
            sat2_r <= '0';
        elsif rising_edge(clk) then
            vout_r <= '0';

            case st2 is
                when E2_IDLE =>
                    if e2_go = '1' then
                        ch2  <= 0;
                        tap2 <= 0;
                        acc2 <= (others => '0');
                        -- newest written slot; wrap explicitly, D2 is not 2^n
                        if wp2 = 0 then
                            rp2 <= to_unsigned(D2-1, AW2);
                        else
                            rp2 <= wp2 - 1;
                        end if;
                        st2  <= E2_ADDR;
                    end if;

                when E2_ADDR =>
                    -- Conditional subtract, not mod: D2 is not a power of two.
                    oa := to_integer(rp2) - C_IDX2(tap2);
                    ob := to_integer(rp2) - (C_N2-1 - C_IDX2(tap2));
                    if oa < 0 then oa := oa + D2; end if;
                    if ob < 0 then ob := ob + D2; end if;
                    ia := ch2*D2 + oa;
                    ib := ch2*D2 + ob;
                    a2_a <= signed(ram2(ia));
                    a2_b <= signed(ram2(ib));
                    cf2  <= C_COEF2(tap2);
                    if C_IDX2(tap2) = (C_N2-1)/2 then
                        mid2 <= '1';
                    else
                        mid2 <= '0';
                    end if;
                    st2 <= E2_MAC;

                when E2_MAC =>
                    if mid2 = '1' then
                        pre := resize(a2_a, DW+1);
                    else
                        pre := resize(a2_a, DW+1) + resize(a2_b, DW+1);
                    end if;
                    prod := pre * cf2;
                    acc2 <= acc2 + resize(prod, C_ACC_BITS);

                    if tap2 = F2-1 then
                        st2 <= E2_DONE;
                    else
                        tap2 <= tap2 + 1;
                        st2  <= E2_ADDR;
                    end if;

                when E2_DONE =>
                    if is_sat(acc2) then
                        sat2_r <= '1';
                    end if;
                    out_reg(383 - ch2*DW downto 384 - (ch2+1)*DW)
                        <= std_logic_vector(round_sat(acc2));
                    acc2 <= (others => '0');
                    tap2 <= 0;

                    if ch2 = CH-1 then
                        vout_r <= '1';        -- all 16 channels updated
                        st2    <= E2_IDLE;
                    else
                        ch2 <= ch2 + 1;
                        st2 <= E2_ADDR;
                    end if;
            end case;
        end if;
    end process;

    -- Stage-2 delay line: one true-dual-port RAM. Port A carries the write and
    -- the first read; port B carries the second read.
    process(clk)
    begin
        if rising_edge(clk) then
            if wr2_en = '1' then
                ram2(wr2_addr) <= wr2_data;
            end if;
        end if;
    end process;

end architecture rtl;
