# ======================================================================
# TDM_UATR.sdc - Hardware Timing Constraints
# ======================================================================

# 1. Base Clocks: Tell Quartus about the physical 50 MHz clocks
create_clock -name clk_50m -period 20.000 [get_ports {clk_50m_board}]
create_clock -name rmii_clk -period 20.000 [get_ports {rmii_ref_clk}]

# 2. PLL Magic: Tell Quartus to automatically calculate the 12.288 MHz 
# and 18.432 MHz clocks generated by our ALTPLL module.
derive_pll_clocks
derive_clock_uncertainty

# 3. Asynchronous Domains: We don't want the compiler failing the build 
# trying to synchronize the 50 MHz logic with the 18.432 MHz logic.
# We tell it to ignore paths between them.
set_clock_groups -asynchronous \
    -group [get_clocks {clk_50m rmii_clk}] \
    -group [get_clocks {u_pll|altpll_component|auto_generated|pll1|clk[*]}]

# 4. ADAU1978 I/O Delays: 
# The ADAU1978 datasheet states a max 18 ns delay from the clock edge to valid data.
# The audio clock is whichever PLL output top_system selects via C_FS_48K:
#   clk[0] = 12.288 MHz -> 48 kHz     clk[1] = 18.432 MHz -> 72 kHz
# Only the one that is actually used gets a derived clock, so pick whichever
# exists. Hardcoding clk[1] meant these constraints were silently DROPPED after
# the switch to 48 kHz - "Ignored set_input_delay ... empty collection".
# Whichever PLL output top_system maps to clk_18m is the audio clock:
#   clk[0] 12.288 MHz (48k)   clk[1] 18.432 MHz (72k)   clk[2] 24.576 MHz (96k)
# Only the connected one gets a derived clock, so take the first that resolves.
# Hardcoding one meant these constraints were silently DROPPED whenever the rate
# changed - "Ignored set_input_delay ... empty collection" - leaving the audio
# domain completely unconstrained in timing analysis.
set bclk_net [get_clocks -nowarn u_pll|altpll_component|auto_generated|pll1|clk[0]]
foreach idx {1 2} {
    if {[get_collection_size $bclk_net] == 0} {
        set bclk_net [get_clocks -nowarn u_pll|altpll_component|auto_generated|pll1|clk[$idx]]
    }
}
if {[get_collection_size $bclk_net] == 0} {
    post_message -type error "SDC: no PLL audio clock resolved - check top_system port map"
}

set_input_delay  -clock $bclk_net -max 18.0 [get_ports {sdata_in_A sdata_in_B}]
set_input_delay  -clock $bclk_net -min  0.0 [get_ports {sdata_in_A sdata_in_B}]

# 5. RMII PHY Interface (LAN8720A)
# The FPGA and the PHY are both clocked by rmii_ref_clk, so these are real
# source-synchronous paths and must be constrained or the fitter places them
# with arbitrary delay.
#
# TX: the PHY samples TXD/TX_EN on the rising edge of REF_CLK and requires
# 4 ns of setup and 2 ns of hold. Output delay max = tsu, min = -thold.
set_output_delay -clock rmii_clk -max  4.0 [get_ports {rmii_txd[*] rmii_tx_en}]
set_output_delay -clock rmii_clk -min -2.0 [get_ports {rmii_txd[*] rmii_tx_en}]

# RX: the PHY launches RXD/CRS_DV from the same REF_CLK edge. The window below
# is clock-to-out plus board skew.
# NOTE: verify these two numbers against your LAN8720A datasheet and PCB trace
# lengths. If setup fails, the usual fixes are packing the capture registers
# into the IOBs or capturing on a phase-shifted clock - do not just relax them.
set_input_delay  -clock rmii_clk -max 14.0 [get_ports {rmii_rxd[*] rmii_crs_dv}]
set_input_delay  -clock rmii_clk -min  4.0 [get_ports {rmii_rxd[*] rmii_crs_dv}]

# 6. False Paths (Ignored I/O)

# Ignore I2C pins (Async and very slow compared to the 50MHz clock)
set_false_path -to [get_ports {i2c_scl i2c_sda}]
set_false_path -from [get_ports {i2c_scl i2c_sda}]

# Static levels, LEDs, and the asynchronous reset button - no timing relationship
set_false_path -to   [get_ports {phy_rst_n eth_mdc eth_mdio}]
set_false_path -from [get_ports {eth_mdio}]
set_false_path -to   [get_ports {test_led debug_led_rx debug_led_tx}]
set_false_path -to   [get_ports {en_15v en_48v buffer_state}]
set_false_path -to   [get_ports {adc_rst_n}]