# ======================================================================
# TDM_UATR.sdc - Hardware Timing Constraints
# ======================================================================

# 1. Base Clock: Tell Quartus about the physical 50 MHz crystal
create_clock -name clk_50m -period 20.000 [get_ports {clk_50m}]

# 2. PLL Magic: Tell Quartus to automatically calculate the 12.288 MHz 
# and 18.432 MHz clocks generated by our ALTPLL module.
derive_pll_clocks
derive_clock_uncertainty

# 3. Asynchronous Domains: We don't want the compiler failing the build 
# trying to synchronize the 50 MHz logic with the 18.432 MHz logic.
# We tell it to ignore paths between them.
set_clock_groups -asynchronous \
    -group [get_clocks {clk_50m}] \
    -group [get_clocks {u_pll|altpll_component|auto_generated|pll1|clk[*]}]

# 4. ADAU1978 I/O Delays: 
# The ADAU1978 datasheet states a max 18 ns delay from the clock edge to valid data.
# We map these to the auto-generated 18.432 MHz BCLK (which is clk[1] in the PLL).
set bclk_net [get_clocks {u_pll|altpll_component|auto_generated|pll1|clk[1]}]

set_input_delay  -clock $bclk_net -max 18.0 [get_ports {sdata_in_A sdata_in_B}]
set_input_delay  -clock $bclk_net -min  0.0 [get_ports {sdata_in_A sdata_in_B}]

# Ignore the slow digital tube display pins so they don't clog the analyzer
set_false_path -to [get_ports {dig[*] seg[*]}]