# ======================================================================
# TDM_UATR.sdc - Hardware Timing Constraints
# ======================================================================

# 1. Base Clocks: Tell Quartus about the physical 50 MHz clocks
create_clock -name clk_50m -period 20.000 [get_ports {clk_50m_board}]
create_clock -name rmii_clk -period 20.000 [get_ports {rmii_ref_clk}]

# 2. PLL Magic: Tell Quartus to automatically calculate the 12.288 MHz 
# and 18.432 MHz clocks generated by our ALTPLL module.
derive_pll_clocks
derive_clock_uncertainty

# 3. Asynchronous Domains: We don't want the compiler failing the build 
# trying to synchronize the 50 MHz logic with the 18.432 MHz logic.
# We tell it to ignore paths between them.
# THREE groups, not two. clk_50m and rmii_clk were in the SAME group, which
# declares them synchronous to each other - but clk_50m_board is the dev board's
# own 50 MHz crystal and rmii_ref_clk is REF_CLK out of the LAN8720A, off its own
# crystal. Two unrelated oscillators that happen to share a nominal frequency.
# Grouped together, any register-to-register path between them is analysed
# against a fictitious 20 ns relationship and reported as met, when it is really
# an unsynchronised clock domain crossing.
#
# There is no such path in the design today - the clk_50m_board domain holds only
# the heartbeat divider, the reset and power sequencers and the PLL/reset fault
# counters, and everything it sends elsewhere is either a false-pathed output pin
# or goes through a 2-FF synchroniser. Separating the groups keeps it that way:
# add a path between them later and the timing analyser will now say so instead
# of quietly passing it.
set_clock_groups -asynchronous \
    -group [get_clocks {clk_50m}] \
    -group [get_clocks {rmii_clk}] \
    -group [get_clocks {u_pll|altpll_component|auto_generated|pll1|clk[*]}]

# 4. ADAU1978 I/O Delays: 
# The ADAU1978 datasheet states a max 18 ns delay from the clock edge to valid data.
# The audio clock is whichever PLL output top_system selects via C_FS_48K:
#   clk[0] = 12.288 MHz -> 48 kHz     clk[1] = 18.432 MHz -> 72 kHz
# Only the one that is actually used gets a derived clock, so pick whichever
# exists. Hardcoding clk[1] meant these constraints were silently DROPPED after
# the switch to 48 kHz - "Ignored set_input_delay ... empty collection".
# Whichever PLL output top_system maps to clk_18m is the audio clock:
#   clk[0] 12.288 MHz (48k)   clk[1] 18.432 MHz (72k)   clk[2] 24.576 MHz (96k)
# Only the connected one gets a derived clock, so take the first that resolves.
# Hardcoding one meant these constraints were silently DROPPED whenever the rate
# changed - "Ignored set_input_delay ... empty collection" - leaving the audio
# domain completely unconstrained in timing analysis.
# Resolve the INDEX once, then build both the clock and the pin path from it.
# create_generated_clock -source needs a pin/port/node, not a clock collection,
# so a clock object alone is not enough - passing one gets the whole constraint
# silently dropped with "Argument -source is a collection that is not of port,
# pin, reg, kpr, net, comb or node type".
set audio_idx -1
foreach idx {0 1 2} {
    set c [get_clocks -nowarn "u_pll|altpll_component|auto_generated|pll1|clk\[$idx\]"]
    if {[get_collection_size $c] > 0} {
        set audio_idx $idx
        break
    }
}
if {$audio_idx < 0} {
    post_message -type error "SDC: no PLL audio clock resolved - check top_system port map"
} else {
    post_message -type info "SDC: audio clock is PLL clk\[$audio_idx\]"
}
set bclk_node "u_pll|altpll_component|auto_generated|pll1|clk\[$audio_idx\]"
set bclk_net  [get_clocks $bclk_node]

# BCLK leaves the FPGA as a forwarded copy of the audio clock (top_system does
# bclk_out <= clk_18m). Declare it as a generated clock on the port, otherwise
# neither it nor LRCLK is analysed at all - and until 2026-08-10 neither was.
# There was no set_output_delay on bclk_out or lrclk_out anywhere in this file,
# so the fitter placed the two with arbitrary relative delay. That skew comes
# straight off the LRCLK setup budget at the ADC, which is the margin the whole
# TDM framing depends on.
create_generated_clock -name bclk_pin -source [get_pins $bclk_node] -divide_by 1 \
    [get_ports {bclk_out}]

# LRCLK is DATA with respect to BCLK. The numbers and the reference edge now come
# from the datasheet rather than being guessed - Table 5, ADC SERIAL PORT:
#
#   tALS   10 ns min   LRCLK setup to BCLK RISING, slave mode
#   tALH    5 ns min   LRCLK hold from BCLK RISING, slave mode
#   tABDD  18 ns max   SDATAOUTx delay from BCLK falling
#
# So the part LATCHES LRCLK ON THE RISING EDGE of BCLK, and drives SDATAOUT from
# the falling edge. Those are different edges and both are correct: BCLKEDGE
# (0x04 bit 6) = 0 makes the falling edge the OUTPUT launch edge, which is what
# Table 19 describes and what tABDD confirms. It does not move the LRCLK input
# sampling edge, and this file previously assumed it did.
#
# -clock_fall was therefore wrong: it analysed LRCLK against the falling edge,
# half a BCLK away from where the part actually samples it. That made the budget
# a half period (20.3 ns) when the real relationship is launch on rising edge N
# to sample on rising edge N+1, a full period. The constraint was PESSIMISTIC,
# not loose, so it never caused a failure - but the slack it reported understated
# the real margin by about 2x, and the fitter was optimising the wrong skew.
#
# SIGN. tALH is a HOLD requirement at the ADC and must be entered as a NEGATIVE
# min output delay: -min -5.0, not +5.0. set_output_delay states delay EXTERNAL
# to the port, and TimeQuest SUBTRACTS it from the required time in both checks:
#     required(setup) = latch_edge + T - output_delay_max
#     required(hold)  = latch_edge     - output_delay_min
# so a positive -min makes hold EASIER by exactly that amount, not harder. The
# previous +5.0 therefore relaxed the check by 10 ns relative to the truth and
# turned a real violation into a comfortable pass.
#
# Confirmed against the tool's own arithmetic on the 2026-08-16 report, where
# both rows reconcile to within the same 0.110 ns of clock uncertainty:
#     setup  40.695 - 10.0 + 2.670 - 4.488 = 28.877  reported 28.767
#     hold            4.161 - 2.904 + 5.0  =  6.257  reported  6.147
# The hold row only balances if the +5.0 is ADDED, which is the bug.
#
# The physical number underneath, which needs no sign convention at all: LRCLK
# leaves its pad only 4.161 - 2.904 = 1.26 ns (min) to 4.488 - 2.670 = 1.82 ns
# (max) after BCLK leaves its pad, and Table 5 requires 5 ns. See tdm8_master.
#
# LAUNCH CLOCK. As of the phase-shift change, lrclk_out is NOT launched by the
# same clock as bclk_out. top_system registers it onto PLL output c3, a phase
# shifted 24.576 MHz copy of c2, purely to move the transition off the half
# period a falling-edge launch is stuck at. Nothing below needed to change:
# derive_pll_clocks picks c3 up automatically, and the clk[*] wildcard in the
# clock group above already declares c2 and c3 synchronous, which they are.
#
# These two constraints are therefore the readout for whether the phase landed
# where it was meant to. Against the pre-shift baseline of setup +8.382 /
# hold +16.520 (Slow 85C), expect roughly:
#
#   105 deg (11870 ps)   setup ~ +16.5    hold ~  +9.0
#   225 deg (25431 ps)   setup ~  +3.0    hold ~ +22.5
#
# CHECK THE EDGE PAIR, DO NOT ASSUME IT. With a phase shifted launch clock
# TimeQuest picks whichever launch/capture pair yields worst-case slack, and
# that is not always the one intended. If setup and hold have not moved in
# OPPOSITE directions by about 8.5 ns from the baseline, the tool chose a
# different pair and this needs a set_multicycle_path - do not program the
# device until those two numbers reconcile. This file has already shipped one
# constraint that read plausibly and had its sign inverted; see
# LRCLK_HOLD_VIOLATION.md.
set_output_delay -clock bclk_pin -max  10.0 [get_ports {lrclk_out}]
set_output_delay -clock bclk_pin -min  -5.0 [get_ports {lrclk_out}]

# SDATA is launched by the ADC on the falling edge of BCLK (tABDD, 18 ns max)
# and tdm8_rx now captures it on the falling edge of the internal clock.
#
# REFERENCE CLOCK. This was "-clock $bclk_net", the INTERNAL PLL output. That is
# not the clock the ADC launches from: the part is clocked by the copy that left
# the FPGA on bclk_out and went through U2. Referencing the internal node omits
# the entire clock-forwarding delay, and the report shows exactly how much that
# is - bclk_pin arrives 1.559 to 2.904 ns after the PLL clock reaches the core
# (the "Clock Skew" column on the lrclk_out rows). Add U2 at 1.5-2.5 ns and the
# cable, and the analysis was crediting the design with 5-7 ns it does not have.
# "-clock bclk_pin" makes TimeQuest walk the real path to the pad.
#
# Board delays are declared rather than buried. Adjust if the harness changes.
#   BCLK_TO_ADC   bclk_out pad -> U2 -> ADC BCLK pin
#   SDATA_TO_FPGA ADC SDATAOUTx pin -> sdata_in_x pad (no buffer in this path)
set bclk_to_adc_max   2.5
set bclk_to_adc_min   1.5
set sdata_to_fpga_max 1.0
set sdata_to_fpga_min 0.3
#
# max: worst case the data can be late  = clock out + tABDD max + data back
# min: best case it can be early. The datasheet gives no minimum for tABDD, so 0
# is the only defensible floor - pessimistic for hold, which is the safe side.
set_input_delay -clock bclk_pin -clock_fall \
    -max [expr $bclk_to_adc_max + 18.0 + $sdata_to_fpga_max] \
    [get_ports {sdata_in_A sdata_in_B}]
set_input_delay -clock bclk_pin -clock_fall \
    -min [expr $bclk_to_adc_min +  0.0 + $sdata_to_fpga_min] \
    [get_ports {sdata_in_A sdata_in_B}]

# 5. RMII PHY Interface (LAN8720A)
# The FPGA and the PHY are both clocked by rmii_ref_clk, so these are real
# source-synchronous paths and must be constrained or the fitter places them
# with arbitrary delay.
#
# TX: the PHY samples TXD/TX_EN on the rising edge of REF_CLK and requires
# 4 ns of setup and 2 ns of hold. Output delay max = tsu, min = -thold.
set_output_delay -clock rmii_clk -max  4.0 [get_ports {rmii_txd[*] rmii_tx_en}]
set_output_delay -clock rmii_clk -min -2.0 [get_ports {rmii_txd[*] rmii_tx_en}]

# RX: the PHY launches RXD/CRS_DV from the same REF_CLK edge. The window below
# is clock-to-out plus board skew.
# NOTE: verify these two numbers against your LAN8720A datasheet and PCB trace
# lengths. If setup fails, the usual fixes are packing the capture registers
# into the IOBs or capturing on a phase-shifted clock - do not just relax them.
set_input_delay  -clock rmii_clk -max 14.0 [get_ports {rmii_rxd[*] rmii_crs_dv}]
set_input_delay  -clock rmii_clk -min  4.0 [get_ports {rmii_rxd[*] rmii_crs_dv}]

# 6. False Paths (Ignored I/O)

# Ignore I2C pins (Async and very slow compared to the 50MHz clock)
set_false_path -to [get_ports {i2c_scl i2c_sda}]
set_false_path -from [get_ports {i2c_scl i2c_sda}]

# Static levels, LEDs, and the asynchronous reset button - no timing relationship
set_false_path -to   [get_ports {phy_rst_n eth_mdc eth_mdio}]
set_false_path -from [get_ports {eth_mdio}]
set_false_path -to   [get_ports {test_led debug_led_rx debug_led_tx}]
set_false_path -to   [get_ports {en_15v en_48v buffer_state}]
set_false_path -to   [get_ports {adc_rst_n}]