#!/usr/bin/env python3
"""
mixer_gui_standalone.py - the UATR_TDM mixer + telemetry GUI in ONE file.

    python mixer_gui_standalone.py                  # 16 meters + faders
    python mixer_gui_standalone.py --gdat-connect   # also dial the aux_vcu
    python mixer_gui_standalone.py --gdat-buoy 3 --gdat-connect

No imports from any other file in its directory - copy this one file wherever
you like. It does use numpy and tkinter: numpy is an installed library (the same
one the real GUI uses), tkinter ships with CPython.

  DO NOT EDIT THIS FILE. It is GENERATED by make_gui_standalone.py, which
  extracts its inlined copies of the telemetry decoder, the packet geometry and
  the gain law straight out of gdat2.py, imu_test.py, ctrl.py and
  udp_monitor.py. Edit those and re-run the generator:

      python make_gui_standalone.py            # regenerate
      python make_gui_standalone.py --check    # fail if stale

  Editing here instead puts a second, diverging copy of the telemetry field map
  into the world - precisely the fault the telemetry tab exists to detect. A map
  that has shifted one place still frames, still checksums, and still prints
  perfectly formatted values under the wrong headings.

WHAT THE TELEMETRY TAB CHECKS
  Each field carries a "live" column, because a value can frame, checksum,
  decode and print plausibly while never being updated at all:
    live N      the field has been seen to change N times - proven alive
    constant ?  never yet changed. NOT a fault on its own: this firmware
                quantises attitude to 0.1 deg, so a still unit repeats one value
                and is healthy. Move the unit to settle it
    zero        exactly zero forever - the firmware is not filling it
  Out-of-range values turn red in place, which is how a shifted field map shows
  itself: the attitude stays believable, and the leak sensor reads 18 V.
"""

import argparse
import collections
import math
import os
import socket
import struct
import sys
import threading
import time
import tkinter as tk
from tkinter import ttk

import numpy as np


class _NS(object):
    """A stand-in for an imported module, so the GUI body needs no rewriting.

    The body still says gdat2.Link, um.CHANNELS, ctrl.decode,
    imu_test.AxisWindow. Keeping those spellings means this file is the real GUI
    source with its imports satisfied differently, rather than a fork of it that
    would have to be re-reviewed line by line.
    """

    def __init__(self, **kw):
        self.__dict__.update(kw)


# ------------------------------------------------------------------ inlined from udp_monitor.py ---
MAGIC        = bytes([0xAD, 0xA1, 0x97, 0x78])

HDR_LEN      = 10

FRAME_LEN    = 50

FRAMES_PKT   = 8

PAYLOAD_LEN  = HDR_LEN + FRAMES_PKT * FRAME_LEN      # 410

CHANNELS     = 16

SAMPLE_BYTES = 3

FULL_SCALE   = 1 << 23                                # 24-bit signed

SAMPLE_RATE   = 96000

# ------------------------------------------------------------------------- inlined from ctrl.py ---
FPGA_IP   = "192.168.1.101"      # C_FPGA_IP in top_system.vhd, node 1

FPGA_PORT = 5005                 # any port: udp_rx_core does not filter on it

STREAM_PORT = 5005

MUTE = 0xFF

ZERO_DB = 0xA0

PHANTOM_FRAME = 1

def gain_byte(db):
    """dB -> register value. +60 dB at 0x00, -0.375 dB per step."""
    if db is None:
        return MUTE
    v = int(round((60.0 - float(db)) / 0.375))
    return max(0, min(0xFE, v))          # 0xFF is mute, keep it out of range

def gain_db(b):
    return None if b == MUTE else 60.0 - b * 0.375

def send_gain(ch, byte_val, flags=None, ip=FPGA_IP, port=FPGA_PORT):
    """ch is 1-16 as printed by the monitor.

    flags is the optional 3rd payload byte; bit 0 enables 48 V phantom power.
    Pass None to send the original 2-byte packet, which leaves the FPGA's flag
    state untouched. The GUI passes it on every command so phantom state is
    carried explicitly and never depends on what the board happened to latch.
    """
    if not 1 <= ch <= 16:
        raise ValueError("channel must be 1-16")
    idx = ch - 1
    adc, sub = idx // 4, idx % 4
    pkt = [(adc << 2) | sub, byte_val]
    if flags is not None:
        pkt.append(flags & 0xFF)
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        s.sendto(bytes(pkt), (ip, port))
    finally:
        s.close()
    return adc, sub

def send_flags(flags, ip=FPGA_IP, port=FPGA_PORT):
    """Set the control flags without changing a gain.

    Re-sends channel 1's current setting is not possible from here, so this
    addresses ADC 0 channel 0 with 0xA0 (0 dB). Harmless if channel 1 is
    already at 0 dB; the GUI uses its own slider value instead.
    """
    return send_gain(1, ZERO_DB, flags=flags, ip=ip, port=port)

def phantom_state(pkt):
    """Decode the 48 V readback out of one audio packet.

    -> dict, or None if the packet is unusable or the bitstream predates this.

    Phantom power is otherwise write-only, and the command path is not a record
    of the state: the FPGA clears udp_flags on any reset, and a restarted GUI
    starts with its checkbox off while the board may still be driving 48 V. So
    the only trustworthy answer comes from the board itself, in every packet.

    Keys:
        on          the en_48v pin as actually driven
        requested   the host asked for it (udp_flags bit 0)
        staged      the staged power-up passed 1000 ms
        permitted   C_ENABLE_48V is true in this build
    'on' is the AND of the other three, so which one is false names the cause.

    ASSERTED, NOT MEASURED. en_48v is an FPGA output with no sense line back, so
    a dead supply or an open enable trace still reports on.
    """
    if len(pkt) < um.PAYLOAD_LEN or pkt[:4] != um.MAGIC:
        return None
    b = pkt[um.HDR_LEN + PHANTOM_FRAME * um.FRAME_LEN]
    if not b & 0x80:            # marker bit: this byte is populated
        return None
    return {"on":        bool(b & 0x40),
            "requested": bool(b & 0x20),
            "staged":    bool(b & 0x10),
            "permitted": bool(b & 0x08)}

def phantom_reason(st):
    """One line explaining a phantom_state dict, naming the gate that is off."""
    if st is None:
        return "unknown - no packet, or a bitstream older than the readback"
    if st["on"]:
        return "ON - the FPGA is asserting EN_48V"
    if not st["permitted"]:
        return "off - C_ENABLE_48V is false in this build, so it cannot come on"
    if not st["staged"]:
        return "off - the staged power-up has not reached 1000 ms yet"
    if not st["requested"]:
        return "off - not requested. An FPGA reset clears the request, so this " \
               "is also what you see after the board has rebooted under a " \
               "GUI that still shows phantom enabled"
    # All three gates set and the pin still low is the watchdog signature. It
    # needs no status bit of its own precisely because nothing else produces
    # this combination: the host asked for 48 V, the build allows it, the
    # power-up timer reached it, and the FPGA is overriding all three.
    return ("off - the phantom WATCHDOG has tripped. The FPGA has not heard a "
            "flags-carrying packet within C_PHANTOM_TIMEOUT_S and has dropped "
            "48 V on its own. Send any command with a flags byte to restore it")

def decode(payload):
    body = payload[um.HDR_LEN:]
    n = len(body) // um.FRAME_LEN
    if n == 0:
        return None
    raw = np.frombuffer(body[:n * um.FRAME_LEN], dtype=np.uint8)
    raw = raw.reshape(n, um.FRAME_LEN)[:, 2:]
    raw = raw.reshape(n, um.CHANNELS, um.SAMPLE_BYTES).astype(np.int32)
    v = (raw[:, :, 0] << 16) | (raw[:, :, 1] << 8) | raw[:, :, 2]
    return np.where(v & 0x800000, v - 0x1000000, v)

# ------------------------------------------------------------------------ inlined from gdat2.py ---
TALKER   = "GDAT2"

N_RAW    = 10                     # ulRaw[0..9]

DEFAULT_PORT = 8080

BUOYS = (("buoy 1", "192.168.3.110"),
         ("buoy 2", "192.168.3.120"),
         ("buoy 3", "192.168.3.130"),
         ("buoy 4", "192.168.3.140"))

ACTIVE_BUOY  = 3

DEFAULT_HOST = BUOYS[ACTIVE_BUOY - 1][1]

FIELDS = (
    ("Leak sensor",     "V",    "f32"),
    ("Voltage monitor", "V",    "f32"),
    ("Depth",           "m",    "f32"),
    ("Depth temp",      "degC", "f32"),
    ("AHRS Roll",       "deg",  "f32"),
    ("AHRS Pitch",      "deg",  "f32"),
    ("AHRS Yaw",        "deg",  "f32"),
    ("Altimeter dist",  "mm",   "u32"),
    ("Altimeter conf",  "%",    "u32"),
    ("Digital I/O",     "",     "bits"),
)

DIO_OPEN  = 0x01

DIO_CLOSE = 0x02

I_LEAK, I_VBUS, I_DEPTH, I_DTEMP, I_ROLL, I_PITCH, I_YAW, \
    I_ALT_MM, I_ALT_PCT, I_DIO = range(N_RAW)

AHRS_IDX = (I_ROLL, I_PITCH, I_YAW)

PLAUSIBLE = (
    (0.0,    5.0),        # Leak sensor, V - an ADC pin reading, 3.3/5 V rail
    (0.0,   60.0),        # Voltage monitor, V - 24 V nominal bus
    (-2.0,  500.0),       # Depth, m - slightly negative at the surface is real
    (-5.0,   50.0),       # Depth temp, degC - seawater plus self-heating
    (-180.0, 180.0),      # Roll, deg
    (-90.0,   90.0),      # Pitch, deg - a pitch outside this is a convention
                          # error, not an attitude
    (-180.0, 360.0),      # Yaw, deg - see note above, admits both conventions
    (0.0, 100000.0),      # Altimeter dist, mm - 100 m
    (0.0,    100.0),      # Altimeter conf, %
    (0.0,      3.0),      # Digital I/O - only bits 0 and 1 are defined
)

def implausible(vals):
    """-> [(index, value, lo, hi)] for every field outside PLAUSIBLE.

    Undecoded fields (None) are not reported here; they are already an error of
    their own and reporting them twice makes one fault read as two.
    """
    out = []
    for i, v in enumerate(vals):
        if v is None or PLAUSIBLE[i] is None:
            continue
        lo, hi = PLAUSIBLE[i]
        if not (lo <= v <= hi):
            out.append((i, v, lo, hi))
    return out

def checksum(body):
    """NMEA-0183 checksum: XOR of every byte between '$' and '*', exclusive."""
    c = 0
    for ch in body.encode("ascii", "replace"):
        c ^= ch
    return c

def build(raw, seq=0, cnt=0):
    """Encode 10 u32s into a sentence. Used by the simulator and the tests.

    ulRaw as 8 hex digits each, seq and cnt as unsigned decimal ASCII.
    """
    body = "%s,%s,%d,%d" % (TALKER, ",".join("%08X" % (int(v) & 0xFFFFFFFF)
                                             for v in raw), seq, cnt & 0xFF)
    return "$%s*%02X\r\n" % (body, checksum(body))

def f32_bits(x):
    """float -> the u32 that carries it. Inverse of the 'f32' decode."""
    return struct.unpack("<I", struct.pack("<f", float(x)))[0]

def bits_f32(v):
    """u32 -> the float its bits spell."""
    return struct.unpack("<f", struct.pack("<I", int(v) & 0xFFFFFFFF))[0]

_HEX = set("0123456789abcdefABCDEF")

def decode_field(tok, kind):
    """-> (raw_u32_or_None, value_or_None). Strictly 8 hex digits, no prefix.

    Hex is not a guess here, it is the encoding - see ENCODING above. Two traps
    that an earlier decimal-first reading of this fell into, both silent:

      "42280000" is 0x42280000 = 42.0. Read as decimal it is 42,280,000, whose
      bits spell 1.96e-37. Every field is all-digits often enough that this
      would have looked like a working link producing absurd numbers.

      "3E000000" is 0.125. Hex digits include 'E', so any heuristic that treats
      an 'e' as a float exponent turns this into the literal 3.0 - a plausible
      value, silently wrong, on a field that happened to contain an E.

    Hence: no sniffing. The wire format is fixed, so parse it as what it is.
    """
    tok = tok.strip()
    if tok[:2].lower() == "0x":          # tolerated, not expected
        tok = tok[2:]
    if not tok or len(tok) > 8 or any(c not in _HEX for c in tok):
        return None, None
    raw = int(tok, 16)
    if kind == "f32":
        v = bits_f32(raw)
        # NaN/inf means the bits are not a float at all - an integer sent where
        # a float was documented. Report raw so the GUI can say so, not "nan".
        if math.isnan(v) or math.isinf(v):
            return raw, None
        return raw, v
    return raw, float(raw)

def parse(line):
    """Decode one sentence.

    Returns a dict, always - a rejected sentence still reports why. Never
    raises: this sits on a socket fed by another vendor's firmware, and one
    malformed sentence must not take the link down.
    """
    out = {"ok": False, "err": None, "csum_ok": None, "raw": [None] * N_RAW,
           "vals": [None] * N_RAW, "wire": [""] * N_RAW,
           "seq": None, "cnt": None, "line": line, "t": time.time()}

    s = line.strip()
    if not s:
        out["err"] = "empty"
        return out
    if not s.startswith("$"):
        out["err"] = "no '$'"
        return out
    s = s[1:]

    if "*" in s:
        body, _, tail = s.partition("*")
        hh = tail[:2]
        try:
            out["csum_ok"] = (int(hh, 16) == checksum(body))
        except ValueError:
            out["csum_ok"] = False
        if not out["csum_ok"]:
            out["err"] = "checksum (got %s, want %02X)" % (hh, checksum(body))
            # fall through and still decode: a checksum error on an otherwise
            # readable sentence is far more useful shown than discarded, and
            # during bring-up it is usually the checksum convention that is
            # wrong, not the data.
    else:
        body = s                       # no checksum present; not an error

    parts = body.split(",")
    if parts[0] != TALKER:
        out["err"] = "talker %r, want %r" % (parts[0], TALKER)
        return out
    nums = parts[1:]
    if len(nums) < N_RAW:
        out["err"] = "%d fields, need at least %d" % (len(nums), N_RAW)
        return out

    for i in range(N_RAW):
        out["wire"][i] = nums[i].strip()
        out["raw"][i], out["vals"][i] = decode_field(nums[i], FIELDS[i][2])
    if any(r is None for r in out["raw"]) and out["err"] is None:
        bad = [i for i, r in enumerate(out["raw"]) if r is None]
        out["err"] = "field %s not 8-digit hex" % ",".join(str(i) for i in bad)

    # 12 fields = ulRaw + seq + cnt as documented. 11 = no seq. Accept both:
    # the spec's field table lists cnt but not seq, so the sender may well omit
    # it, and refusing the sentence over that would block the whole tab.
    extra = nums[N_RAW:]
    if len(extra) >= 2:
        out["seq"] = _int_or_none(extra[0])
        out["cnt"] = _int_or_none(extra[1])
    elif len(extra) == 1:
        out["cnt"] = _int_or_none(extra[0])

    out["ok"] = out["err"] is None
    return out

def _int_or_none(tok):
    """seq and cnt are unsigned decimal ASCII - base 10, explicitly.

    Not base 0: Python rejects a leading zero there, so a zero-padded "08"
    would have come back None and silently disabled loss counting.
    """
    try:
        return int(tok.strip(), 10)
    except (ValueError, AttributeError):
        return None

def dio_text(raw):
    """Motor actuator state from ulRaw[9]."""
    if raw is None:
        return "-"
    o, c = bool(raw & DIO_OPEN), bool(raw & DIO_CLOSE)
    if o and c:
        return "OPEN+CLOSE (invalid)"
    return "OPEN" if o else "CLOSE" if c else "idle"

class Link(threading.Thread):
    """TCP transport. Reconnects on its own; never raises into the GUI.

    TCP is a byte stream, not a message stream, so sentences are recovered by
    buffering and splitting on newlines. A 20 ms broadcast will routinely land
    two sentences in one recv() and split a third across two, and treating each
    recv() as one message would corrupt roughly every other reading.
    """

    def __init__(self, mode="client", host="127.0.0.1", port=DEFAULT_PORT,
                 on_frame=None):
        super().__init__(daemon=True)
        self.mode, self.host, self.port = mode, host, port
        # Called with every parsed sentence, good or bad, on the link thread.
        # snapshot() only ever shows the LAST sentence, so a consumer that
        # needs each one (imu_test.py, which measures how the attitude moves
        # between frames) would otherwise have to re-parse the tail and drift
        # away from this decoder.
        self.on_frame = on_frame
        self.lock = threading.Lock()
        self.stop = False
        self.sock = None
        self.srv = None
        self.state = "idle"
        self.peer = ""
        self.last = None            # most recent parsed dict
        self.lines = 0              # sentences seen
        self.good = 0
        self.csum_err = 0
        self.parse_err = 0
        self.lost = 0               # from the cnt field
        self.cnt_prev = None
        self.rate = 0.0
        self._rt0 = time.time()
        self._rn = 0
        self.tail = ""              # raw text ring for the GUI

    # -- public ------------------------------------------------------------
    def snapshot(self):
        with self.lock:
            return dict(state=self.state, peer=self.peer, last=self.last,
                        lines=self.lines, good=self.good,
                        csum_err=self.csum_err, parse_err=self.parse_err,
                        lost=self.lost, rate=self.rate, tail=self.tail)

    def close(self):
        self.stop = True
        for s in (self.sock, self.srv):
            try:
                if s:
                    s.close()
            except OSError:
                pass

    # -- internals ---------------------------------------------------------
    def _set(self, state, peer=None):
        with self.lock:
            self.state = state
            if peer is not None:
                self.peer = peer

    def run(self):
        while not self.stop:
            try:
                self._session()
            except OSError as e:
                self._set("error: %s" % e)
            except Exception as e:                  # never kill the thread
                self._set("error: %r" % e)
            if self.stop:
                break
            self._set("reconnecting")
            for _ in range(20):                     # 2 s, but responsive to stop
                if self.stop:
                    return
                time.sleep(0.1)

    def _session(self):
        if self.mode == "server":
            self.srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            self.srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            self.srv.bind(("0.0.0.0", self.port))
            self.srv.listen(1)
            self.srv.settimeout(0.5)
            self._set("listening on :%d" % self.port, peer="")
            while not self.stop:
                try:
                    self.sock, addr = self.srv.accept()
                    break
                except socket.timeout:
                    continue
            else:
                return
            self._set("connected", peer="%s:%d" % addr)
            try:
                self.srv.close()
            except OSError:
                pass
            self.srv = None
        else:
            self._set("connecting to %s:%d" % (self.host, self.port))
            self.sock = socket.create_connection((self.host, self.port),
                                                 timeout=3.0)
            self._set("connected", peer="%s:%d" % (self.host, self.port))

        self.sock.settimeout(0.5)
        buf = b""
        try:
            while not self.stop:
                try:
                    d = self.sock.recv(4096)
                except socket.timeout:
                    continue
                if not d:
                    self._set("peer closed")
                    return
                buf += d
                # Cap the buffer. A peer that sends megabytes without a newline
                # would otherwise grow this without bound.
                if len(buf) > 65536:
                    buf = buf[-4096:]
                while b"\n" in buf:
                    ln, _, buf = buf.partition(b"\n")
                    self._ingest(ln.decode("ascii", "replace").strip("\r"))
        finally:
            try:
                self.sock.close()
            except OSError:
                pass
            self.sock = None

    def _ingest(self, text):
        if not text.strip():
            return
        r = parse(text)
        with self.lock:
            self.lines += 1
            self._rn += 1
            now = time.time()
            if now - self._rt0 >= 0.5:
                self.rate = self._rn / (now - self._rt0)
                self._rt0, self._rn = now, 0
            # The two error buckets are disjoint. A corrupted sentence usually
            # fails the checksum AND the field parse, and counting it in both
            # made one fault read as two independent problems - which is the
            # opposite of what an error tally is for. Checksum wins, because it
            # names the cause; only a sentence with a good (or absent) checksum
            # that still will not decode is "unparsable".
            if r["csum_ok"] is False:
                self.csum_err += 1
                if r["raw"][0] is not None:
                    self.last = r      # readable but failed checksum: still show
            elif r["ok"]:
                self.good += 1
                self.last = r
            else:
                self.parse_err += 1
            # cnt is a u8 that wraps at 256. Anything but +1 is loss - unless it
            # is a restart, which shows up as a large jump and is not counted.
            c = r["cnt"]
            if c is not None:
                if self.cnt_prev is not None:
                    d = (c - self.cnt_prev) & 0xFF
                    if 1 < d < 64:
                        self.lost += d - 1
                self.cnt_prev = c
            self.tail = (self.tail + text + "\n")[-1200:]
        # Outside the lock: a consumer that blocks must not stall the reader,
        # and a consumer that raises must not take the link down - this thread
        # is the whole transport.
        if self.on_frame is not None:
            try:
                self.on_frame(r)
            except Exception:
                pass

# --------------------------------------------------------------------- inlined from imu_test.py ---
DEFAULT_WINDOW_S = 3.0

STILL_MAX  = 5.0        # --expect still: more span than this is not "still"

MOVING_MIN = 0.20       # --expect moving: less span than this is not "moving"

def wrapped_span(vals):
    """Peak-to-peak of an angle series, in degrees, honouring the 360 wrap.

    Yaw crossing north reads 359.5 then 0.5. A plain max-minus-min calls that a
    359 deg swing and every freeze/motion verdict built on it is inverted at the
    one heading the buoy is most likely to sit at. Consecutive differences are
    wrapped into +/-180 and re-accumulated, so the series is unwrapped first.

    This is correct only while the true step between frames is under 180 deg. At
    20 ms that is a 9000 deg/s slew - well past any real vehicle, and past the
    gyro's own range.
    """
    if not vals:
        return 0.0
    acc, out = float(vals[0]), [float(vals[0])]
    for a, b in zip(vals, vals[1:]):
        d = (float(b) - float(a) + 180.0) % 360.0 - 180.0
        acc += d
        out.append(acc)
    return max(out) - min(out)

class AxisWindow(object):
    """Rolling window over one attitude axis, and the verdict it supports.

    Two timescales, and the difference between them is the whole point:

      the WINDOW  answers "is it moving right now"
      the SESSION answers "has it EVER moved", which is what proves it is alive

    An earlier version had only the window, and concluded that a constant value
    meant a dead field on the reasoning that a live AHRS always dithers in its
    low bits. That is false for a quantised output. Buoy 3 reports attitude in
    steps of 0.1 deg, so a stationary unit repeats one bit pattern indefinitely
    and is perfectly healthy - it was called FROZEN and it was not. Only motion
    distinguishes the two, so a constant value is now reported as UNPROVEN and
    the operator is asked to move the unit, rather than being told a wrong
    answer with confidence.
    """

    def __init__(self, name, window_s=DEFAULT_WINDOW_S):
        self.name = name
        self.window_s = window_s
        self.samples = collections.deque()     # (t, raw_u32, value_deg)
        # Session-wide, never evicted. Bounded because a 50 Hz feed left running
        # all day must not grow without limit; the counts are what matter, not
        # the full history.
        self.session_raw = set()
        self.session_vals = set()
        self.changes = 0                       # times the raw value changed
        self._prev_raw = None

    def feed(self, t, raw, val):
        self.samples.append((t, raw, val))
        cut = t - self.window_s
        while self.samples and self.samples[0][0] < cut:
            self.samples.popleft()

        if self._prev_raw is not None and raw != self._prev_raw:
            self.changes += 1
        self._prev_raw = raw
        if len(self.session_raw) < 4096:
            self.session_raw.add(raw)
            if val is not None:
                self.session_vals.add(round(float(val), 6))

    # -- session ----------------------------------------------------------
    @property
    def ever_moved(self):
        """Has this axis ever taken a second value? Proof of life, once true."""
        return self.changes > 0

    def resolution(self):
        """Apparent quantisation step, or None if it cannot be established.

        Reported so a constant reading can be read correctly: at 0.1 deg steps,
        a still unit SHOULD repeat one value. Derived from what arrived rather
        than assumed - a firmware that sends full float precision will show
        None here and its dither is then meaningful again.
        """
        vs = sorted(self.session_vals)
        if len(vs) < 2:
            return None
        for q in (1.0, 0.5, 0.25, 0.1, 0.05, 0.01):
            if all(abs(v / q - round(v / q)) < 1e-4 for v in vs):
                return q
        return None

    # -- derived ----------------------------------------------------------
    @property
    def n(self):
        return len(self.samples)

    @property
    def span(self):
        return wrapped_span([s[2] for s in self.samples if s[2] is not None])

    @property
    def last(self):
        return self.samples[-1][2] if self.samples else None

    @property
    def distinct_raw(self):
        """Distinct raw bit patterns in the window. 1 means frozen."""
        return len(set(s[1] for s in self.samples if s[1] is not None))

    @property
    def all_zero(self):
        return bool(self.samples) and all(s[1] == 0 for s in self.samples)

    def drift_deg_per_min(self):
        """Signed end-to-end rate across the window, wrap-aware.

        On a stationary vehicle this is uncorrected gyro bias on yaw. It is a
        number to report, not to judge: what counts as too much drift depends
        on the mission length, which this script does not know.
        """
        if self.n < 2:
            return 0.0
        (t0, _r0, v0), (t1, _r1, v1) = self.samples[0], self.samples[-1]
        if v0 is None or v1 is None or t1 <= t0:
            return 0.0
        d = (float(v1) - float(v0) + 180.0) % 360.0 - 180.0
        return d / (t1 - t0) * 60.0

    def verdict(self, expect=None, min_samples=10):
        """-> (tag, text). tag is 'ok' | 'warn' | 'unproven' | 'wait'.

        Order matters: ZERO is reported ahead of a constant reading because an
        all-zero field is also constant, and "the firmware never filled this" is
        the more actionable reading of the same evidence. All-zero stays a
        warning - quantisation explains a repeated PLAUSIBLE value, not a field
        that is exactly zero forever.
        """
        if self.n < min_samples:
            return "wait", "%d samples, need %d" % (self.n, min_samples)
        if self.all_zero and not self.ever_moved:
            return "warn", ("ZERO for %.1fs - firmware is not filling this "
                            "field" % self.window_s)

        if self.distinct_raw == 1:
            res = self.resolution()
            step = (" at %g deg resolution" % res) if res else ""
            if self.ever_moved:
                # Already proved alive earlier in this session, so a constant
                # now just means it is sitting still.
                if expect == "moving":
                    return "warn", ("steady%s while motion was expected "
                                    "(moved %d times earlier)"
                                    % (step, self.changes))
                return "ok", ("steady%s - live, moved %d times this session"
                              % (step, self.changes))
            # Never yet seen to change. A quantised sensor sitting still and a
            # field nobody updates are BIT-IDENTICAL. Refuse to guess.
            if expect == "moving":
                return "warn", ("constant%s through expected motion - suspect "
                                "it is not being updated" % step)
            return "unproven", ("constant%s - stationary and not-updated look "
                                "identical here; MOVE the unit to tell them "
                                "apart" % step)

        span = self.span
        if expect == "still" and span > STILL_MAX:
            return "warn", ("span %.2f deg over %.1fs - expected still, "
                            "something is moving it" % (span, self.window_s))
        if expect == "moving" and span < MOVING_MIN:
            return "warn", ("span %.3f deg over %.1fs - expected motion, this "
                            "is dither only" % (span, self.window_s))
        return "ok", "live, span %.3f deg over %.1fs" % (span, self.window_s)

# ----------------------------------------------------------------- module stand-ins ---
um = _NS(MAGIC=MAGIC, HDR_LEN=HDR_LEN, FRAME_LEN=FRAME_LEN,
         FRAMES_PKT=FRAMES_PKT, PAYLOAD_LEN=PAYLOAD_LEN,
         CHANNELS=CHANNELS, SAMPLE_BYTES=SAMPLE_BYTES,
         FULL_SCALE=FULL_SCALE, SAMPLE_RATE=SAMPLE_RATE)
ctrl = _NS(FPGA_IP=FPGA_IP, FPGA_PORT=FPGA_PORT,
           STREAM_PORT=STREAM_PORT, MUTE=MUTE, ZERO_DB=ZERO_DB,
           PHANTOM_FRAME=PHANTOM_FRAME, gain_byte=gain_byte,
           gain_db=gain_db, send_gain=send_gain,
           send_flags=send_flags, phantom_state=phantom_state,
           phantom_reason=phantom_reason, decode=decode)
gdat2 = _NS(TALKER=TALKER, N_RAW=N_RAW, BUOYS=BUOYS,
            ACTIVE_BUOY=ACTIVE_BUOY, DEFAULT_HOST=DEFAULT_HOST,
            DEFAULT_PORT=DEFAULT_PORT, FIELDS=FIELDS,
            PLAUSIBLE=PLAUSIBLE, implausible=implausible,
            dio_text=dio_text, parse=parse, build=build,
            f32_bits=f32_bits, bits_f32=bits_f32, Link=Link)
imu_test = _NS(AxisWindow=AxisWindow, wrapped_span=wrapped_span)

# -------------------------------------------------------------- mixer_gui.py body (verbatim) ---
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Which ADC owns which channels: matches get_i2c_addr in adau_sequencer.vhd and
# the B-part CMAP slot patch, cross-checked against the netlist address straps.
OWNER = ([("U19", "0x11")] * 4 + [("U20", "0x31")] * 4 +
         [("U37", "0x51")] * 4 + [("U38", "0x71")] * 4)

DB_LO   = -100.0
DECODE_MAX = 120        # packets decoded per redraw; see tick()
# How long a 48 V toggle may go unconfirmed before the checkbox snaps back to
# what the board reports. Generous: the command is one UDP datagram and the
# readback is in the very next packet, so anything past this is a refusal or a
# lost packet, not latency.
PH_TIMEOUT_S = 1.5

# Geometry is computed from the live canvas size in Mixer._metrics, not fixed.
# The meters and the faders under them derive every x from ONE ch_w, and the
# fader columns are embedded in the canvas rather than laid out in their own
# grid - two geometry sources that have to agree will eventually not, and a
# fader sitting under the wrong meter is the one misalignment nobody notices
# until they have turned down the wrong hydrophone.
# Deliberately modest. A 1366x768 or 1280x720 laptop is a real target, and a
# 620 px floor there leaves a window that cannot meaningfully be shrunk or put
# side by side with anything. The layout stays legible down to this size - it
# is tested at exactly these numbers.
MIN_W, MIN_H = 880, 560

BG      = "#16181d"
PANEL   = "#1c1f26"
GRID    = "#2c313a"
TEXT    = "#c8ccd4"
DIM     = "#6b7280"
GREEN   = "#3fb950"
AMBER   = "#d29922"
RED     = "#f85149"


def dbfs(v):
    return DB_LO - 40 if v <= 0 else max(DB_LO - 40, 20.0 * np.log10(v / um.FULL_SCALE))


def _clamp(lo, v, hi):
    return max(lo, min(hi, v))


class Receiver(threading.Thread):
    """UDP in its own thread so a slow redraw never costs packets."""

    def __init__(self, port, bind):
        super().__init__(daemon=True)
        self.lock = threading.Lock()
        self.raw, self.pkts, self.lost, self.seq_prev = [], 0, 0, 0
        self.stop = False
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            self.sock.setsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF, 64 << 20)
        except OSError:
            pass
        self.sock.bind((bind, port))
        self.sock.settimeout(0.3)

    def run(self):
        # Keep this loop as cheap as possible. At 96 kHz the board sends 12,000
        # packets/s - 83 us each - and anything expensive here backs up the
        # socket buffer and drops packets. Decoding was originally done per
        # packet with numpy, which could not keep up: the meter showed half the
        # stream and channels near the threshold appeared to flicker. Raw bytes
        # go on a list, and the GUI thread decodes the whole batch at once.
        local = []
        while not self.stop:
            try:
                d = self.sock.recv(2048)
            except socket.timeout:
                if local:
                    self._flush(local)
                    local = []
                continue
            except OSError:
                break               # socket closed on shutdown
            if len(d) < um.PAYLOAD_LEN or d[:4] != um.MAGIC:
                continue
            local.append(d)
            if len(local) >= 64:            # one lock per 64 packets
                self._flush(local)
                local = []

    def _flush(self, batch):
        with self.lock:
            for d in batch:
                seq = struct.unpack(">I", d[4:8])[0]
                self.pkts += 1
                if self.seq_prev and seq > self.seq_prev + 1:
                    self.lost += seq - self.seq_prev - 1
                self.seq_prev = seq
            self.raw.extend(batch)
            if len(self.raw) > 2000:        # cap if the GUI stalls badly
                del self.raw[:-1000]

    def take(self):
        with self.lock:
            b, self.raw = self.raw, []
            n, self.pkts = self.pkts, 0
            return b, n, self.lost


class Mixer(tk.Frame):
    """The 16-channel mixer, as a frame so it can sit in a notebook tab.

    This was a tk.Tk in its own right until the telemetry tab arrived. Window
    concerns - title, geometry, close handling - moved up to App; everything
    below is unchanged apart from packing into self instead of into a root.
    """

    def __init__(self, master, rx, fps, hold, ip):
        super().__init__(master, bg=BG)
        self.rx, self.hold_s, self.ip = rx, hold, ip
        self.period = int(1000 / fps)

        # The checkbox FOLLOWS the board - see _sync_phantom. It starts False
        # only so the widget has a value before the first packet arrives.
        self.phantom = tk.BooleanVar(value=False)
        self.ph_actual = None           # last phantom_state dict, None = unknown
        self.ph_pending = None          # a user toggle awaiting confirmation
        self.ph_wait = 0.0              # how long it has been awaiting it
        self._ph_quiet = 0.0            # seconds since the last packet, for staleness
        self.gain_db = [tk.DoubleVar(value=0.0) for _ in range(um.CHANNELS)]
        self.muted = [tk.BooleanVar(value=False) for _ in range(um.CHANNELS)]

        self.bar = tk.Frame(self, bg=PANEL)
        self.bar.pack(side="bottom", fill="x")
        self._build_controls()

        self.cv = tk.Canvas(self, bg=BG, highlightthickness=0)
        self.cv.pack(side="top", fill="both", expand=True)

        self.m = None                   # layout metrics, set by _relayout
        self._rjob = None               # pending debounced relayout
        self._build_items()
        self.cv.bind("<Configure>", self._on_resize)

        self.held = np.full(um.CHANNELS, DB_LO - 40)
        self.held_age = np.zeros(um.CHANNELS)
        self._job = self.after(self.period, self.tick)

    # --------------------------------------------------------------- layout
    def _metrics(self, w, h):
        """Every coordinate on this tab, derived from the canvas size alone."""
        left  = _clamp(36, int(w * 0.055), 96)
        pad_r = _clamp(6,  int(w * 0.010), 24)
        ch_w  = max(16.0, float(w - left - pad_r) / um.CHANNELS)

        # Ceilings are set high enough that a 4K lab panel actually gets larger
        # text rather than 232 px meters labelled in 11 pt. The upper bounds
        # only exist to stop a very wide, very short window from producing text
        # taller than the meter it labels.
        f_hdr = _clamp(9, int(h * 0.021) + 5, 28)
        f_sub = _clamp(7, f_hdr - 3, 22)
        f_num = _clamp(7, int(ch_w * 0.20), 30)
        f_sml = _clamp(6, int(ch_w * 0.135), 20)

        head = int(f_hdr * 2.1 + f_sub * 2.2) + 8
        r_num = int(f_num * 1.9)                        # rows under the meter
        r_own = r_num + int(f_sml * 2.0)
        r_val = r_own + int(f_sml * 2.0)
        lab_h = r_val + int(f_sml * 1.5)

        # The faders get a share of the height, but the meters are the point of
        # this tab - so when the window is short the faders give ground first,
        # down to a floor where the scale is still draggable.
        fad_h = _clamp(88, int(h * 0.26), 280)
        mh = h - head - lab_h - fad_h - 6
        if mh < 90:
            fad_h = _clamp(58, fad_h + mh - 90, 280)
            mh = h - head - lab_h - fad_h - 6
        mh = max(36, mh)

        return {"w": w, "h": h, "left": left, "ch_w": ch_w, "top": head,
                "mh": mh, "r_num": r_num, "r_own": r_own, "r_val": r_val,
                "fad_y": head + mh + lab_h,
                "fad_h": fad_h,
                "sc_len": max(34, fad_h - int(f_sml * 2.3) * 2 - 6),
                "sc_wid": _clamp(7, int(ch_w * 0.20), 20),
                "inset": max(2, int(ch_w * 0.12)),
                "bar_in": max(3, int(ch_w * 0.17)),
                "f_hdr": f_hdr, "f_sub": f_sub, "f_num": f_num, "f_sml": f_sml}

    def cx(self, i):
        """Centre of channel i. The meter and its fader both use only this."""
        m = self.m
        return m["left"] + (i + 0.5) * m["ch_w"]

    def _on_resize(self, ev):
        if ev.width < 60 or ev.height < 60:
            return
        # Debounced: a drag fires Configure continuously, and relaying out on
        # every one of them makes the window crawl.
        if self._rjob:
            self.after_cancel(self._rjob)
        self._rjob = self.after(40, self._relayout)

    # ---------------------------------------------------------------- items
    def _build_items(self):
        """Create every canvas item and fader widget once; _relayout moves them.

        Rebuilding on each resize would churn 100+ items and destroy/recreate
        live Scale widgets, losing their drag state mid-gesture.
        """
        self.hdr = self.cv.create_text(0, 0, anchor="w", fill=TEXT, text="")
        self.sub = self.cv.create_text(0, 0, anchor="w", fill=DIM, text="")
        self.rules = []
        for db in range(0, int(DB_LO) - 1, -20):
            self.rules.append((db,
                               self.cv.create_line(0, 0, 0, 0, fill=GRID),
                               self.cv.create_text(0, 0, anchor="e", fill=DIM,
                                                   text="%d" % db)))
        self.gainlab = self.cv.create_text(0, 0, anchor="e", fill=DIM,
                                           text="gain dB")
        self.boxes, self.bars, self.peaks = [], [], []
        self.nums, self.owners, self.labels = [], [], []
        self.seps, self.fadwin = [], []
        for i in range(um.CHANNELS):
            self.boxes.append(self.cv.create_rectangle(0, 0, 0, 0,
                                                       outline=GRID, fill=PANEL))
            self.bars.append(self.cv.create_rectangle(0, 0, 0, 0,
                                                      outline="", fill=GREEN))
            self.peaks.append(self.cv.create_line(0, 0, 0, 0, fill="#ffffff"))
            self.nums.append(self.cv.create_text(0, 0, fill=TEXT,
                                                 text=str(i + 1)))
            who, addr = OWNER[i]
            self.owners.append(self.cv.create_text(0, 0, fill=DIM,
                                                   text="%s %s" % (who, addr)))
            self.labels.append(self.cv.create_text(0, 0, fill=DIM, text="-inf"))
            if i in (4, 8, 12):
                self.seps.append((i, self.cv.create_line(0, 0, 0, 0, fill=GRID)))

            col = tk.Frame(self.cv, bg=BG)
            s = tk.Scale(col, from_=60.0, to=-35.625, resolution=0.375,
                         orient="vertical", width=11, showvalue=False,
                         variable=self.gain_db[i],
                         bg=BG, fg=TEXT, troughcolor=PANEL, highlightthickness=0,
                         activebackground=GREEN, borderwidth=0,
                         command=lambda _v, ch=i: self.on_gain(ch))
            s.pack()
            lab = tk.Label(col, text="0.0", bg=BG, fg=TEXT)
            lab.pack()
            mt = tk.Checkbutton(col, text="M", variable=self.muted[i],
                                command=lambda ch=i: self.on_gain(ch),
                                bg=BG, fg=RED, selectcolor=PANEL,
                                activebackground=BG, activeforeground=RED,
                                borderwidth=0, highlightthickness=0)
            mt.pack()
            # Embedded in the canvas at the meter's own centre, so a fader can
            # never drift out from under the channel it controls.
            self.fadwin.append(self.cv.create_window(0, 0, window=col,
                                                     anchor="n"))
            setattr(self, "_glab%d" % i, lab)
            setattr(self, "_scale%d" % i, s)
            setattr(self, "_mute%d" % i, mt)

    def _relayout(self):
        self._rjob = None
        w, h = self.cv.winfo_width(), self.cv.winfo_height()
        if w < 60 or h < 60:
            return
        m = self.m = self._metrics(w, h)
        cvi, cvc = self.cv.itemconfigure, self.cv.coords
        hf, sf = ("Consolas", m["f_hdr"], "bold"), ("Consolas", m["f_sub"])
        nf, mf = ("Consolas", m["f_num"], "bold"), ("Consolas", m["f_sml"])

        cvc(self.hdr, 12, int(m["f_hdr"] * 1.3)); cvi(self.hdr, font=hf)
        cvc(self.sub, 12, int(m["f_hdr"] * 2.6)); cvi(self.sub, font=sf)
        right = m["left"] + um.CHANNELS * m["ch_w"] - m["inset"]
        for db, ln, tx in self.rules:
            y = self.y_of(db)
            cvc(ln, m["left"] - 6, y, right, y)      # ends at the last meter
            cvc(tx, m["left"] - 11, y); cvi(tx, font=mf)
        cvc(self.gainlab, m["left"] - 11, m["fad_y"] + m["sc_len"] * 0.5)
        cvi(self.gainlab, font=mf)

        bot = m["top"] + m["mh"]
        for i in range(um.CHANNELS):
            c = self.cx(i)
            ins, bin_ = m["inset"], m["bar_in"]
            cvc(self.boxes[i], c - m["ch_w"] / 2 + ins, m["top"],
                c + m["ch_w"] / 2 - ins, bot)
            cvc(self.peaks[i], c - m["ch_w"] / 2 + ins, bot,
                c + m["ch_w"] / 2 - ins, bot)
            cvc(self.bars[i], c - m["ch_w"] / 2 + bin_, bot,
                c + m["ch_w"] / 2 - bin_, bot)
            cvc(self.nums[i], c, bot + m["r_num"]);  cvi(self.nums[i], font=nf)
            cvc(self.owners[i], c, bot + m["r_own"])
            cvi(self.owners[i], font=("Consolas", max(6, m["f_sml"] - 1)))
            cvc(self.labels[i], c, bot + m["r_val"]); cvi(self.labels[i], font=mf)
            cvc(self.fadwin[i], c, m["fad_y"])
            getattr(self, "_scale%d" % i).config(length=m["sc_len"],
                                                 width=m["sc_wid"])
            getattr(self, "_glab%d" % i).config(font=mf)
            getattr(self, "_mute%d" % i).config(font=mf)
        for i, ln in self.seps:
            x = m["left"] + i * m["ch_w"]
            cvc(ln, x, m["top"] - 8, x, m["fad_y"] + m["fad_h"])

    # -------------------------------------------------------------- controls
    def _build_controls(self):
        tk.Button(self.bar, text="all 0 dB", command=lambda: self.set_all(0.0),
                  bg=PANEL, fg=TEXT, font=("Consolas", 9), borderwidth=0,
                  activebackground=GRID, padx=10).pack(side="left", padx=6, pady=6)
        tk.Button(self.bar, text="all mute", command=lambda: self.set_all(None),
                  bg=PANEL, fg=TEXT, font=("Consolas", 9), borderwidth=0,
                  activebackground=GRID, padx=10).pack(side="left", padx=2)
        self.ph = tk.Checkbutton(
            self.bar, text=" 48 V PHANTOM ", variable=self.phantom,
            command=self.on_phantom, bg=PANEL, fg=AMBER, selectcolor="#3a1d1d",
            activebackground=PANEL, activeforeground=RED,
            font=("Consolas", 10, "bold"), borderwidth=0, highlightthickness=0)
        self.ph.pack(side="left", padx=(18, 4))
        # What the board reports it is driving, from the readback in every
        # packet. Normally it agrees with the checkbox; it turns red while a
        # toggle is still in flight or has not taken effect.
        self.ph_lab = tk.Label(self.bar, text="board: ?", bg=PANEL, fg=DIM,
                               font=("Consolas", 9))
        self.ph_lab.pack(side="left", padx=(0, 14))
        self.status = tk.Label(self.bar, text="ready", bg=PANEL, fg=DIM,
                               font=("Consolas", 8), anchor="e")
        self.status.pack(side="right", padx=10)

    # ----------------------------------------------------------------- logic
    def flags(self):
        """The flags byte to attach to an outgoing command.

        This is the BOARD's current phantom state, not the checkbox - and that
        difference is the whole point of the method.

        This GUI is not the only thing driving the board. The operator app owns
        phantom power; this is a debugger watching alongside it. There is no
        flags-only packet - the FPGA parses one command format and every gain
        write carries the flags byte - so if this returned the checkbox, then
        any fader moved here would re-assert whatever phantom state this GUI
        last knew about and silently revert a change the app had made.

        Returning the readback makes a gain command phantom-NEUTRAL: it tells
        the board to keep doing what it is already doing. Only on_phantom, where
        the user actually clicked, sends a value that differs.

        Falls back to the checkbox when the board has not been heard from, which
        is the old single-controller behaviour and the best available guess.
        """
        if self.ph_pending is not None:
            return 0x01 if self.ph_pending else 0x00
        if self.ph_actual is not None:
            return 0x01 if self.ph_actual["on"] else 0x00
        return 0x01 if self.phantom.get() else 0x00

    def send(self, ch):
        """ch is 0-based here; ctrl.send_gain takes 1-16."""
        db = None if self.muted[ch].get() else self.gain_db[ch].get()
        b = ctrl.gain_byte(db)
        try:
            ctrl.send_gain(ch + 1, b, flags=self.flags(), ip=self.ip)
        except OSError as e:
            self.status.config(text="send failed: %s" % e, fg=RED)
            return
        getattr(self, "_glab%d" % ch).config(
            text="mute" if db is None else "%.1f" % db,
            fg=RED if db is None else TEXT)
        self.status.config(
            text="ch %d -> 0x%02X  %s   48V %s"
                 % (ch + 1, b, "mute" if db is None else "%+.3f dB" % db,
                    "ON" if self.phantom.get() else "off"),
            fg=DIM)

    def on_gain(self, ch):
        self.send(ch)

    def on_phantom(self):
        """The ONE place this GUI deliberately changes phantom power.

        Everything else it sends is phantom-neutral - see flags(). A click here
        raises ph_pending, which flags() then sends in place of the readback
        until the board is seen to agree.
        """
        on = self.phantom.get()
        self.ph_pending = on
        self.ph_wait = 0.0
        self.ph.config(fg=RED if on else AMBER)
        self.send(0)            # any command carries the flags byte
        self.status.config(text="48 V %s requested" % ("ON" if on else "off"),
                           fg=RED if on else DIM)

    def _sync_phantom(self, pkt, dt):
        """Mirror the checkbox to whatever the board reports it is driving.

        This GUI FOLLOWS the board; it does not hold an opinion of its own. The
        operator app owns phantom power - it forces 48 V off at every start and
        reload, and from then on only a deliberate user toggle turns it on - so
        the truth lives in the FPGA, and this display exists to show it. An
        earlier version seeded the checkbox once at startup and then let the two
        drift apart, which was right when this GUI was the only controller and
        wrong now: the app can change phantom at any moment, and a debugger
        showing a stale toggle is worse than showing nothing.

        The one exception is a click the user just made. ph_pending holds it,
        the display stays on the requested value while the command is in flight,
        and the board's own readback is what confirms it. That is deliberately
        not a local assumption of success - if the FPGA refuses (C_ENABLE_48V
        false in the build, or the staged power-up not yet at 1000 ms) the
        checkbox snaps back and says so, rather than showing an ON that never
        happened.
        """
        st = ctrl.phantom_state(pkt)
        if st is None:
            return
        self.ph_actual = st

        if self.ph_pending is not None:
            if st["on"] == self.ph_pending:
                self.ph_pending = None          # the board agrees; done
            else:
                self.ph_wait += dt
                if self.ph_wait < PH_TIMEOUT_S:
                    self.ph_lab.config(
                        text="board: %s  (waiting)"
                             % ("ON" if st["on"] else "off"), fg=AMBER)
                    return
                # It has had long enough. Name the gate holding it off - "build"
                # and "power-up" are refusals the user cannot fix from here, and
                # saying which one beats a bare "it did not work".
                why = ("C_ENABLE_48V false in this build" if not st["permitted"]
                       else "staged power-up not at 1000 ms yet"
                       if not st["staged"] else
                       "the FPGA did not receive it" if not st["requested"]
                       else "watchdog has tripped - the FPGA is overriding")
                self.ph_pending = None
                self.phantom.set(st["on"])
                self.ph.config(fg=RED if st["on"] else AMBER)
                self.status.config(text="48 V refused: %s" % why, fg=RED)

        on = st["on"]
        if self.phantom.get() != on:
            # Display only. This writes the BooleanVar, not the hardware: Tk
            # does not fire the widget's command on a programmatic set, so
            # following the board here can never send a packet.
            self.phantom.set(on)
            self.ph.config(fg=RED if on else AMBER)
        self.ph_lab.config(text="board: %s" % ("ON" if on else "off"),
                           fg=RED if on else DIM)

    def set_all(self, db):
        for i in range(um.CHANNELS):
            self.muted[i].set(db is None)
            if db is not None:
                self.gain_db[i].set(db)
            self.send(i)
            self.update_idletasks()

    def y_of(self, db):
        m = self.m
        db = max(DB_LO, min(0.0, db))
        return m["top"] + m["mh"] - (db - DB_LO) / (-DB_LO) * m["mh"]

    def tick(self):
        # The first Configure may not have arrived yet. Reschedule rather than
        # return, or a late Configure would leave the meters never updating.
        if self.m is None:
            self._job = self.after(self.period, self.tick)
            return
        raw, npk, lost = self.rx.take()
        # 48 V readback, from the newest packet in hand. One packet per tick is
        # enough - the state changes on human timescales - and it must be read
        # before the stride below, which is free to drop the newest one.
        if raw:
            self._ph_quiet = 0.0
            self._sync_phantom(raw[-1], self.period / 1000.0)
        else:
            self._ph_quiet += self.period / 1000.0
            if self._ph_quiet > 2.0 and self.ph_actual is not None:
                # Stop showing a reading the board is no longer confirming. The
                # pin has not necessarily changed - the link has - but an
                # indicator that keeps asserting "off" for an unplugged board is
                # exactly the kind of thing that gets trusted around live 48 V.
                self.ph_actual = None
                self.ph_lab.config(text="board: ? (no packets)", fg=AMBER)
        # Decode a bounded, evenly-spread subset rather than everything. Full
        # decode runs at ~9,000 pkt/s against a 12,000 pkt/s stream, so the GUI
        # would fall further behind every frame and channels near the threshold
        # would flicker. 120 packets is 960 frames per channel per update -
        # far more than RMS and peak need - and the stride keeps it
        # representative of the whole window rather than just the oldest part.
        if len(raw) > DECODE_MAX:
            raw = raw[::max(1, len(raw) // DECODE_MAX)][:DECODE_MAX]
        blocks = [b for b in (ctrl.decode(d) for d in raw) if b is not None]
        if blocks:
            x = np.concatenate(blocks, axis=0).astype(np.float64)
            rms = np.sqrt(np.mean(x * x, axis=0))
            pk = np.max(np.abs(x), axis=0)
        else:
            rms = pk = np.zeros(um.CHANNELS)

        pps = npk * (1000.0 / self.period)
        self.cv.itemconfigure(self.hdr, text="%d Hz   %5.0f pkt/s   lost %d"
                              % (um.SAMPLE_RATE, pps, lost))
        self.cv.itemconfigure(self.sub, text="bar = RMS   white = held peak   "
                                             "faders write ADAU1978 reg 0x0A-0x0D over I2C")

        step = self.period / 1000.0
        m = self.m
        bot, half = m["top"] + m["mh"], m["ch_w"] / 2
        for i in range(um.CHANNELS):
            rdb, pdb = dbfs(rms[i]), dbfs(pk[i])
            silent = rdb < -120
            clipped = pk[i] >= um.FULL_SCALE - 1
            self.held_age[i] += step
            if pdb >= self.held[i] or self.held_age[i] > self.hold_s:
                self.held[i], self.held_age[i] = pdb, 0.0

            c = self.cx(i)
            y = self.y_of(rdb)
            self.cv.coords(self.bars[i], c - half + m["bar_in"], y,
                           c + half - m["bar_in"], bot)
            self.cv.itemconfigure(self.bars[i], fill=(
                DIM if silent else RED if rdb > -6 else AMBER if rdb > -20 else GREEN))
            yp = self.y_of(self.held[i])
            self.cv.coords(self.peaks[i], c - half + m["inset"], yp,
                           c + half - m["inset"], yp)
            self.cv.itemconfigure(self.peaks[i], fill=RED if clipped else "#ffffff")
            self.cv.itemconfigure(
                self.labels[i],
                text="SILENT" if silent else ("CLIP" if clipped else "%.0f" % rdb),
                fill=DIM if silent else (RED if clipped else TEXT))

        self._job = self.after(self.period, self.tick)

    def close(self):
        """Release the socket. The window itself is App's to destroy."""
        # Cancel BOTH pending callbacks first. Destroying the window with one
        # still queued makes Tk fire it against a dead widget and print
        # "invalid command name ...tick" on every exit. The debounced relayout
        # is the same hazard on a resize-then-close, just harder to trip.
        for attr in ("_job", "_rjob"):
            if getattr(self, attr, None):
                self.after_cancel(getattr(self, attr))
                setattr(self, attr, None)
        self.rx.stop = True
        try:
            self.rx.sock.close()
        except OSError:
            pass


class Telemetry(tk.Frame):
    """$GDAT2 sensor telemetry from the aux_vcu, over TCP.

    A different device on a different transport from everything else here, so
    it shares no state with the mixer beyond the window - if the aux_vcu is
    absent or the FPGA is unplugged, the other tab carries on regardless.

    ulRaw fields arrive as 8 hex digits; seq and cnt as decimal. The wire text
    is shown next to the decoded value for every field, so a decode that goes
    wrong can be checked against the bytes that produced it without a capture.
    """

    ROW_H = 26

    def __init__(self, master, mode, host, port, fps=10.0):
        super().__init__(master, bg=BG)
        self.period = int(1000 / fps)
        self.link = None
        self.mode = tk.StringVar(value=mode)
        self.host = tk.StringVar(value=host)
        self.port = tk.StringVar(value=str(port))
        self._rjob = None
        self._build()
        self.bind("<Configure>", self._on_resize)
        # A notebook tab that has never been shown is unmapped and 1x1, and
        # Configure does not fire on it - so a window resized while the Mixer
        # tab was in front would leave this one still at its build-time font
        # sizes. Map fires when it first becomes visible; rescale then.
        self.bind("<Map>", self._on_resize)
        self._job = self.after(self.period, self.tick)

    # Font sizes track the window so the table stays readable on a 4K panel and
    # still fits on a laptop. Column widths are weighted, so the table stretches
    # rather than stranding everything against the left edge in fullscreen.
    def _on_resize(self, _ev=None):
        # Deliberately does not read _ev: this handles <Map> too, whose width
        # and height are not the real geometry. _rescale asks the widget.
        if self._rjob:
            self.after_cancel(self._rjob)
        self._rjob = self.after(60, self._rescale)

    def _rescale(self):
        self._rjob = None
        w, h = self.winfo_width(), self.winfo_height()
        if w < 60 or h < 60:
            return
        base = _clamp(8, int(min(w / 105.0, h / 46.0)), 20)
        cell = ("Consolas", base)
        big = ("Consolas", base + 1)
        for row in self.cells:
            for i, lab in enumerate(row):
                lab.config(font=big if i == 3 else cell)
        self.stats.config(font=cell)
        for lab in self.heads:
            lab.config(font=("Consolas", max(7, base - 1)))
        self.rawbox.config(font=("Consolas", max(7, base - 1)))

    def pick_buoy(self, name):
        for nm, ip in gdat2.BUOYS:
            if nm == name:
                # Set the label too. The OptionMenu writes the variable itself
                # before calling this, but a programmatic call does not, and
                # then the label would name one buoy while the socket talked to
                # another - the one disagreement this selector must not allow.
                self.buoy.set(nm)
                self.host.set(ip)
                if self.link:           # retarget an open link immediately
                    self.toggle()
                    self.toggle()
                break

    # ------------------------------------------------------------- layout --
    def _build(self):
        bar = tk.Frame(self, bg=PANEL)
        bar.pack(fill="x")
        tk.Label(bar, text=" aux_vcu ", bg=PANEL, fg=TEXT,
                 font=("Consolas", 10, "bold")).pack(side="left", padx=(8, 2), pady=7)
        # Start the selector on whichever buoy --gdat-host names, so the label
        # and the address can never disagree about what is being talked to.
        here = self.host.get().strip()
        self.buoy = tk.StringVar(
            value=next((n for n, ip in gdat2.BUOYS if ip == here), "custom"))
        om = tk.OptionMenu(bar, self.buoy, *[n for n, _ip in gdat2.BUOYS],
                           command=self.pick_buoy)
        om.config(bg=GRID, fg=TEXT, font=("Consolas", 9), borderwidth=0,
                  highlightthickness=0, activebackground=GREEN, width=7)
        om["menu"].config(bg=PANEL, fg=TEXT, font=("Consolas", 9))
        om.pack(side="left", padx=(4, 8))
        for txt, val in (("client", "client"), ("server", "server")):
            tk.Radiobutton(bar, text=txt, value=val, variable=self.mode,
                           bg=PANEL, fg=TEXT, selectcolor=GRID,
                           activebackground=PANEL, activeforeground=TEXT,
                           font=("Consolas", 8), borderwidth=0,
                           highlightthickness=0).pack(side="left")
        tk.Entry(bar, textvariable=self.host, width=15, bg=BG, fg=TEXT,
                 insertbackground=TEXT, font=("Consolas", 9),
                 borderwidth=0).pack(side="left", padx=(10, 2))
        tk.Label(bar, text=":", bg=PANEL, fg=DIM).pack(side="left")
        tk.Entry(bar, textvariable=self.port, width=6, bg=BG, fg=TEXT,
                 insertbackground=TEXT, font=("Consolas", 9),
                 borderwidth=0).pack(side="left", padx=2)
        self.btn = tk.Button(bar, text="connect", command=self.toggle,
                             bg=GRID, fg=TEXT, font=("Consolas", 9),
                             borderwidth=0, activebackground=GREEN, padx=12)
        self.btn.pack(side="left", padx=10)
        self.state_lab = tk.Label(bar, text="idle", bg=PANEL, fg=DIM,
                                  font=("Consolas", 8), anchor="e")
        self.state_lab.pack(side="right", padx=10)

        self.stats = tk.Label(self, text="", bg=BG, fg=DIM, anchor="w",
                              font=("Consolas", 9), justify="left")
        self.stats.pack(fill="x", padx=12, pady=(8, 4))

        # The "live" column is the one that stops a number being believed just
        # because it is well formatted. A field can frame, checksum, decode and
        # print a plausible value while never being updated at all - which is
        # what 1.1/3.1/177.7 deg of attitude did on buoy 3 until someone picked
        # the unit up. Tracking is imu_test's, imported rather than reimplemented.
        cols = (("field", 150, "w"), ("wire (hex)", 120, "e"),
                ("u32", 110, "e"), ("value", 130, "e"), ("unit", 60, "w"),
                ("live", 110, "w"))
        # weight per column, so the table uses the whole width when maximised
        wts = (3, 2, 2, 2, 1, 2)
        head = tk.Frame(self, bg=BG)
        head.pack(fill="x", padx=12)
        self.heads = []
        for i, (nm, _w, _a) in enumerate(cols):
            head.grid_columnconfigure(i, weight=wts[i], uniform="tel")
            lab = tk.Label(head, text=nm, bg=BG, fg=DIM, font=("Consolas", 8),
                           anchor="w")
            lab.grid(row=0, column=i, sticky="ew")
            self.heads.append(lab)

        self.grid_f = tk.Frame(self, bg=PANEL)
        self.grid_f.pack(fill="x", padx=12, pady=(2, 8))
        self.cells = []
        for i in range(len(cols)):
            self.grid_f.grid_columnconfigure(i, weight=wts[i], uniform="tel")
        # One tracker per field, session-wide. Reset on connect, not per frame:
        # "has this ever changed" is only meaningful over a whole session, and
        # is the only thing that separates a sensor sitting still from a field
        # nobody writes. See imu_test.AxisWindow.
        self.watch = [imu_test.AxisWindow(nm) for nm, _u, _k in gdat2.FIELDS]
        self.last_t = None

        for r, (nm, unit, _k) in enumerate(gdat2.FIELDS):
            row = []
            bgc = PANEL if r % 2 == 0 else BG
            for i, (_h, _w, anch) in enumerate(cols):
                txt = nm if i == 0 else (unit if i == 4 else "-")
                fg = TEXT if i in (0, 3) else DIM
                lab = tk.Label(self.grid_f, text=txt, bg=bgc, fg=fg,
                               font=("Consolas", 10 if i == 3 else 9),
                               anchor=anch, padx=4, pady=3)
                lab.grid(row=r, column=i, sticky="ew")
                row.append(lab)
            self.cells.append(row)

        tk.Label(self, text="last sentences", bg=BG, fg=DIM,
                 font=("Consolas", 8), anchor="w").pack(fill="x", padx=12)
        self.rawbox = tk.Text(self, height=6, bg=PANEL, fg=DIM,
                              font=("Consolas", 8), borderwidth=0,
                              highlightthickness=0, wrap="none")
        self.rawbox.pack(fill="both", expand=True, padx=12, pady=(2, 10))

    # -------------------------------------------------------------- logic --
    def toggle(self):
        if self.link:
            self.link.close()
            self.link = None
            self.btn.config(text="connect", activebackground=GREEN)
            self.state_lab.config(text="disconnected", fg=DIM)
            return
        try:
            port = int(self.port.get())
        except ValueError:
            self.state_lab.config(text="bad port", fg=RED)
            return
        # A fresh link is a fresh session: carrying "it moved earlier" across a
        # reconnect would let a dead field inherit a previous unit's proof.
        for w in self.watch:
            w.__init__(w.name)
        self.last_t = None
        self.link = gdat2.Link(self.mode.get(), self.host.get().strip(), port)
        self.link.start()
        self.btn.config(text="disconnect", activebackground=RED)

    def tick(self):
        if self.link:
            s = self.link.snapshot()
            ok = s["state"] == "connected"
            self.state_lab.config(
                text="%s  %s" % (s["state"], s["peer"]),
                fg=GREEN if ok else AMBER if "connect" in s["state"] else RED)
            self.stats.config(
                text="%6.1f sentence/s   good %-7d checksum err %-5d "
                     "unparsable %-5d counter loss %-5d"
                     % (s["rate"], s["good"], s["csum_err"], s["parse_err"],
                        s["lost"]),
                fg=RED if (s["csum_err"] or s["parse_err"]) else DIM)

            r = s["last"]
            # Stale is its own state. A frozen connection shows the last good
            # reading forever otherwise, which is the one failure a telemetry
            # view must never present as live data.
            stale = r is None or (time.time() - r["t"]) > 1.0

            # Feed the liveness trackers, but only on a sentence we have not
            # already seen - snapshot() returns the same "last" between ticks,
            # and re-feeding it would pad the sample counts with duplicates.
            # This samples at the GUI tick rate rather than every frame, which
            # undercounts changes but cannot invent one: what matters is
            # whether a field EVER changes, and that survives sampling.
            if r is not None and r["t"] != self.last_t:
                self.last_t = r["t"]
                for i in range(len(gdat2.FIELDS)):
                    if r["raw"][i] is not None:
                        self.watch[i].feed(r["t"], r["raw"][i], r["vals"][i])

            # Out-of-range says the SENTENCE is suspect, most likely a shifted
            # field map, so it is flagged per field rather than as one banner.
            bad_range = set()
            if r is not None:
                bad_range = set(i for i, _v, _lo, _hi
                                in gdat2.implausible(r["vals"]))

            for i, (_nm, unit, kind) in enumerate(gdat2.FIELDS):
                raw = r["raw"][i] if r else None
                val = r["vals"][i] if r else None
                c = self.cells[i]
                c[1].config(text=(r["wire"][i] or "-") if r else "-",
                            fg=RED if (r and raw is None) else DIM)
                c[2].config(text="-" if raw is None else str(raw))
                if kind == "bits":
                    txt = gdat2.dio_text(raw)
                    fg = GREEN if txt in ("OPEN", "CLOSE") else \
                        RED if "invalid" in txt else DIM
                elif val is None:
                    # raw None = the token was not 8 hex digits at all.
                    # raw set but val None = bits that spell NaN/inf, i.e. not
                    # a float. Different faults, so they read differently.
                    txt, fg = ("not a float" if raw is not None
                               else "bad hex"), RED
                else:
                    txt = "%.3f" % val if kind == "f32" else "%d" % val
                    fg = RED if i in bad_range else TEXT
                c[3].config(text=txt, fg=DIM if stale else fg)

                # Liveness. "constant" is deliberately not red: on this firmware
                # attitude is quantised to 0.1 deg, so a still unit repeats one
                # value and that is healthy. Amber means unproven - move the
                # unit and watch it go green - not broken. Exact zero forever is
                # a different claim and does read as a fault.
                w = self.watch[i]
                if not w.session_raw:
                    lv, lfg = "-", DIM
                elif w.ever_moved:
                    lv, lfg = "live  %d" % w.changes, GREEN
                elif w.session_raw == {0}:
                    lv, lfg = "zero", RED
                else:
                    res = w.resolution()
                    lv = "constant ?" + (" %gd" % res if res else "")
                    lfg = AMBER
                c[5].config(text=lv, fg=DIM if stale else lfg)
            if stale and r is not None:
                self.state_lab.config(text="STALE - no sentence for >1 s",
                                      fg=RED)
            elif r is not None and r["csum_ok"] is False:
                # These numbers came off a sentence that failed its checksum, so
                # they are shown but not trusted. Saying so is the difference
                # between a reading and a guess.
                self.state_lab.config(text="CHECKSUM FAILED - values suspect",
                                      fg=RED)

            if s["tail"] != self.rawbox.get("1.0", "end-1c"):
                self.rawbox.delete("1.0", "end")
                self.rawbox.insert("1.0", s["tail"])
                self.rawbox.see("end")
        self._job = self.after(self.period, self.tick)

    def close(self):
        for attr in ("_job", "_rjob"):          # see Mixer.close
            if getattr(self, attr, None):
                self.after_cancel(getattr(self, attr))
                setattr(self, attr, None)
        if self.link:
            self.link.close()
            self.link = None


class App(tk.Tk):
    """Window shell. Owns the notebook and shuts both tabs down cleanly."""

    def __init__(self, a):
        super().__init__()
        self.title("UATR Control Station")
        self.configure(bg=BG)
        self.minsize(MIN_W, MIN_H)

        # Open at a sensible fraction of the actual screen rather than a fixed
        # size - this runs on both a laptop and the lab's big panel, and a
        # hardcoded geometry is wrong on one of them.
        sw, sh = self.winfo_screenwidth(), self.winfo_screenheight()
        w, h = max(MIN_W, int(sw * 0.78)), max(MIN_H, int(sh * 0.82))
        self.geometry("%dx%d+%d+%d" % (w, h, (sw - w) // 2, max(0, (sh - h) // 3)))
        if getattr(a, "fullscreen", False):
            self.attributes("-fullscreen", True)
        elif getattr(a, "maximized", False):
            self._zoom()

        self._fs = bool(getattr(a, "fullscreen", False))
        self.bind("<F11>", self.toggle_fullscreen)
        self.bind("<Escape>", self.exit_fullscreen)

        style = ttk.Style(self)
        try:
            style.theme_use("clam")          # the only stock theme that lets
        except tk.TclError:                  # tab colours be set on Windows
            pass
        style.configure("TNotebook", background=BG, borderwidth=0)
        style.configure("TNotebook.Tab", background=PANEL, foreground=DIM,
                        padding=(16, 7), font=("Consolas", 10), borderwidth=0)
        style.map("TNotebook.Tab", background=[("selected", GRID)],
                  foreground=[("selected", TEXT)])

        nb = self.nb = ttk.Notebook(self)
        nb.pack(fill="both", expand=True)

        self.rx = Receiver(a.port, a.bind)
        self.rx.start()
        self.mixer = Mixer(nb, self.rx, a.fps, a.peak_hold, a.ip)
        self.tel = Telemetry(nb, a.gdat_mode, a.gdat_host, a.gdat_port)
        nb.add(self.mixer, text="Mixer")
        nb.add(self.tel, text="Telemetry")

        if a.gdat_connect:
            self.tel.toggle()
        self.protocol("WM_DELETE_WINDOW", self.close)

    def _zoom(self):
        """Maximise. 'zoomed' is Windows/macOS; X11 wants the WM hint."""
        try:
            self.state("zoomed")
        except tk.TclError:
            try:
                self.attributes("-zoomed", True)
            except tk.TclError:
                pass

    def toggle_fullscreen(self, _ev=None):
        self._fs = not self._fs
        self.attributes("-fullscreen", self._fs)
        return "break"

    def exit_fullscreen(self, _ev=None):
        # Escape only leaves fullscreen; it must not close the window, which is
        # what an unguarded Escape binding on the root would end up doing.
        if self._fs:
            self._fs = False
            self.attributes("-fullscreen", False)
        return "break"

    def close(self):
        self.mixer.close()
        self.tel.close()
        self.destroy()


def main():
    ap = argparse.ArgumentParser(description="UATR control station GUI")
    ap.add_argument("--port", type=int, default=5005)
    ap.add_argument("--bind", default="0.0.0.0")
    ap.add_argument("--fps", type=float, default=20.0)
    ap.add_argument("--peak-hold", type=float, default=2.0)
    ap.add_argument("--ip", default=ctrl.FPGA_IP, help="board IP for control")
    ap.add_argument("--gdat-host", default=gdat2.DEFAULT_HOST,
                    help="aux_vcu address (client mode)")
    ap.add_argument("--gdat-buoy", type=int, choices=(1, 2, 3, 4),
                    help="pick the buoy by number instead of --gdat-host (%s)"
                         % ", ".join("%d=%s" % (i + 1, ip)
                                     for i, (_n, ip) in enumerate(gdat2.BUOYS)))
    ap.add_argument("--gdat-port", type=int, default=gdat2.DEFAULT_PORT)
    ap.add_argument("--gdat-mode", choices=("client", "server"),
                    default="client",
                    help="client dials the aux_vcu, server waits for it")
    ap.add_argument("--gdat-connect", action="store_true",
                    help="open the telemetry link at startup")
    ap.add_argument("--fullscreen", action="store_true",
                    help="start fullscreen (F11 toggles, Escape leaves)")
    ap.add_argument("--maximized", action="store_true",
                    help="start maximised")
    a = ap.parse_args()
    if a.gdat_buoy:
        a.gdat_host = gdat2.BUOYS[a.gdat_buoy - 1][1]
    App(a).mainloop()


if __name__ == "__main__":
    main()
